-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '06 Apr 2026 20:22'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '06 Apr 2026 20:19'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '06 Apr 2026 20:17'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '06 Apr 2026 20:15'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '06 Apr 2026 20:12'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '06 Apr 2026 20:06'::timestamp),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', 'Fishcracks - Slumber Party', '06 Apr 2026 20:03'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'terminal oden od', '06 Apr 2026 19:57'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the sus files', '06 Apr 2026 19:55'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the cashier looked at me weird i don''t know if i can go back', '06 Apr 2026 19:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'new notification dopamine', '06 Apr 2026 19:50'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'this is the daria i''ve ever made', '06 Apr 2026 19:49'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'LONG LIVE THE KING', '06 Apr 2026 19:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'unabomber arc', '06 Apr 2026 19:44'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'PUPLIFE', '06 Apr 2026 19:41'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'DOGPIT', '06 Apr 2026 19:39'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'puppydog''s lament', '06 Apr 2026 19:38'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'LEASH', '06 Apr 2026 19:36'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'AUTISM BE DAMNED!', '06 Apr 2026 19:33'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - MiKU MUST DiE', '06 Apr 2026 18:23'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '06 Apr 2026 15:52'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '06 Apr 2026 15:51'::timestamp),
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '06 Apr 2026 15:49'::timestamp),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', 'Fishcracks - Slumber Party', '06 Apr 2026 15:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'scene kweenz', '06 Apr 2026 15:45'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'v0id', '06 Apr 2026 15:44'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'your local menace to society', '06 Apr 2026 15:42'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '06 Apr 2026 15:37'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'wanna fucking scream!!!', '06 Apr 2026 15:35'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '06 Apr 2026 15:32'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', '21', '06 Apr 2026 14:39'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'supa girl racer 5', '06 Apr 2026 14:37'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re fake as fuck', '06 Apr 2026 14:35'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'this is the daria i''ve ever made', '06 Apr 2026 14:34'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'five nights at jason derulo''s', '06 Apr 2026 14:32'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'black tar heroin', '06 Apr 2026 14:29'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nice opinion one small issue', '06 Apr 2026 14:26'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '06 Apr 2026 14:25'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '06 Apr 2026 14:23'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nothing makes sense and i''m lost', '06 Apr 2026 14:21'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'z-mecha', '06 Apr 2026 14:20'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'z-mecha', '05 Apr 2026 20:12'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'stay high', '05 Apr 2026 20:09'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the sus files', '05 Apr 2026 19:33'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bad crack style 2012', '05 Apr 2026 19:31'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the cashier looked at me weird i don''t know if i can go back', '05 Apr 2026 19:28'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'new notification dopamine', '05 Apr 2026 19:26'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nah i''m out of title ideas', '05 Apr 2026 19:22'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'classically trained in dariacore', '05 Apr 2026 19:21'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'gr!ndcore or something idk im hxrny', '05 Apr 2026 19:20'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'scene kweenz', '05 Apr 2026 19:18'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'old money bitch', '05 Apr 2026 19:14'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'your local menace to society', '05 Apr 2026 19:12'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'hound down', '05 Apr 2026 19:10'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '05 Apr 2026 19:09'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'sadb0i dariacore', '05 Apr 2026 19:07'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '05 Apr 2026 19:04'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'glue monkey', '05 Apr 2026 19:03'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'rock that microphone', '05 Apr 2026 19:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'terminal oden od', '05 Apr 2026 18:59'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '05 Apr 2026 18:55'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'move like a freak!', '05 Apr 2026 18:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'v0id', '05 Apr 2026 18:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'let me oute!!!', '05 Apr 2026 18:49'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'feeling lucky', '05 Apr 2026 18:47'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'wanna fucking scream!!!', '05 Apr 2026 18:45'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bxphomet goatmilk 🜏 666', '05 Apr 2026 18:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '04 Apr 2026 22:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '04 Apr 2026 22:26'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '04 Apr 2026 22:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '04 Apr 2026 22:23'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '04 Apr 2026 22:21'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '04 Apr 2026 22:19'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '04 Apr 2026 22:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '04 Apr 2026 22:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '04 Apr 2026 22:14'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '04 Apr 2026 22:13'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '04 Apr 2026 22:11'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '04 Apr 2026 22:09'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '04 Apr 2026 22:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '04 Apr 2026 22:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '04 Apr 2026 22:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '04 Apr 2026 22:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '04 Apr 2026 22:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '04 Apr 2026 21:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '04 Apr 2026 21:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '04 Apr 2026 21:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '04 Apr 2026 21:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '04 Apr 2026 21:53'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '04 Apr 2026 21:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '04 Apr 2026 21:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '04 Apr 2026 21:48'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '04 Apr 2026 21:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '04 Apr 2026 21:44'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Coronach', '04 Apr 2026 21:39'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'The Art of Resurrection', '04 Apr 2026 21:34'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Sculptor''s Cave', '04 Apr 2026 21:29'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Mortercheyn', '04 Apr 2026 21:25'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Blakk Satanik Fvkkstorm', '04 Apr 2026 21:21'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'What Went Weird', '04 Apr 2026 21:21'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Mastodon Matador', '04 Apr 2026 21:19'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Threat Level Midnight', '04 Apr 2026 21:17'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Ah Uh Oh', '04 Apr 2026 21:16'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Introductory Remarks', '04 Apr 2026 21:14'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Snaggle Tooth', '04 Apr 2026 21:13'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'The Big Unit', '04 Apr 2026 21:12'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Distant Rumbling / Closing Remarks', '04 Apr 2026 21:11'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Do You Have Cowboy Hat', '04 Apr 2026 21:10'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Blink Blink Blink', '04 Apr 2026 21:09'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Tous Les Jours', '04 Apr 2026 21:08'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Kelly''s Dungeon', '04 Apr 2026 21:07'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Sweet Thing', '04 Apr 2026 19:47'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Cool Hold Music', '04 Apr 2026 19:46'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Near Death Bossa Nova', '04 Apr 2026 19:45'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Hypemanda Mk I', '04 Apr 2026 19:44'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Bad at Texting / World''s Last Mango Juul Pod', '04 Apr 2026 19:43'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Snaggle Tooth', '04 Apr 2026 16:30'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Mastodon Matador', '04 Apr 2026 16:28'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Ah Uh Oh', '04 Apr 2026 16:26'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'The Big Unit', '04 Apr 2026 16:25'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Introductory Remarks', '04 Apr 2026 16:24'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Threat Level Midnight', '04 Apr 2026 16:23'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'What Went Weird', '04 Apr 2026 16:21'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'NEWGROUNDS HITMAN', '04 Apr 2026 16:17'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'VEGETARIAN', '04 Apr 2026 16:16'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'YEAR OF THE NAUGHTY FOX', '04 Apr 2026 16:13'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Blazing in the Dark', '04 Apr 2026 16:11'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '04 Apr 2026 16:10'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '04 Apr 2026 16:10'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '04 Apr 2026 16:08'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '04 Apr 2026 16:05'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '04 Apr 2026 16:03'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '04 Apr 2026 16:00'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '04 Apr 2026 15:58'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '04 Apr 2026 15:55'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '04 Apr 2026 15:55'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '04 Apr 2026 15:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '02 Apr 2026 22:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '02 Apr 2026 22:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '02 Apr 2026 22:03'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '02 Apr 2026 22:02'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '02 Apr 2026 22:00'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '02 Apr 2026 21:57'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '02 Apr 2026 21:55'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '02 Apr 2026 21:53'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '02 Apr 2026 21:50'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '02 Apr 2026 21:47'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '02 Apr 2026 21:45'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '02 Apr 2026 21:43'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WELCOME 2 STAY @ HOME SUMMER', '02 Apr 2026 21:43'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '02 Apr 2026 21:41'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '02 Apr 2026 21:39'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '02 Apr 2026 21:36'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '02 Apr 2026 21:35'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'SAME PLACE DIFFERENT TIME', '02 Apr 2026 21:03'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PROTECC ATTACC SEXYBACC', '02 Apr 2026 21:00'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THE MAKE UP BEAR', '02 Apr 2026 20:54'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ÄLSKAR DIG!!', '02 Apr 2026 20:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO! ÒwÓ', '02 Apr 2026 20:50'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MY DOG RUNS ON SOYLENT', '02 Apr 2026 20:46'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MYSPACE BANGER 3008', '02 Apr 2026 20:45'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'I REALLY REALLY REALLY HATE THE WORLD BUT THAT''S OK AT LEAST I''VE GOT MY GABBER DRUM', '02 Apr 2026 20:43'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'NAMx', '02 Apr 2026 20:40'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PROTECC ATTACC SEXYBACC', '02 Apr 2026 20:38'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THE MAKE UP BEAR', '02 Apr 2026 20:36'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ÄLSKAR DIG!!', '02 Apr 2026 20:32'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO! ÒwÓ', '02 Apr 2026 20:30'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - POWERHAUS 2014', '02 Apr 2026 20:29'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '02 Apr 2026 20:27'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '02 Apr 2026 20:25'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '02 Apr 2026 20:22'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '02 Apr 2026 18:00'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '02 Apr 2026 17:58'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '02 Apr 2026 17:56'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - ASS UP!', '02 Apr 2026 17:55'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '02 Apr 2026 17:53'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '02 Apr 2026 17:48'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '02 Apr 2026 17:47'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '02 Apr 2026 17:39'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '02 Apr 2026 17:37'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '02 Apr 2026 17:34'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '02 Apr 2026 17:32'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '02 Apr 2026 17:28'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '02 Apr 2026 17:26'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '02 Apr 2026 17:23'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '02 Apr 2026 17:21'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '02 Apr 2026 17:20'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Blazing in the Dark', '02 Apr 2026 17:18'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '02 Apr 2026 17:15'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '02 Apr 2026 16:16'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '02 Apr 2026 16:14'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '02 Apr 2026 16:11'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '02 Apr 2026 16:09'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '02 Apr 2026 16:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '02 Apr 2026 16:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '02 Apr 2026 16:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '02 Apr 2026 16:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '02 Apr 2026 15:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '02 Apr 2026 15:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '02 Apr 2026 15:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '02 Apr 2026 15:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '02 Apr 2026 15:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '02 Apr 2026 15:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '02 Apr 2026 15:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '02 Apr 2026 15:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '02 Apr 2026 15:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '02 Apr 2026 15:36'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '02 Apr 2026 15:34'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '02 Apr 2026 15:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '02 Apr 2026 15:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '02 Apr 2026 15:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '02 Apr 2026 15:24'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '02 Apr 2026 15:22'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'A CYBER''S WORLD?', '01 Apr 2026 22:07'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'A Real Boy!', '01 Apr 2026 22:06'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Cyber Battle', '01 Apr 2026 22:05'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'The Legend', '01 Apr 2026 22:04'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Field of Hopes And Dreams', '01 Apr 2026 22:01'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Imminent Death', '01 Apr 2026 22:01'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Your Power', '01 Apr 2026 22:01'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Quiet Autumn', '01 Apr 2026 22:00'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'GALLERY', '01 Apr 2026 22:00'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Susie', '01 Apr 2026 21:59'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Fanfare', '01 Apr 2026 21:59'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'School', '01 Apr 2026 21:57'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'A Town Called Hometown', '01 Apr 2026 21:56'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'basement', '01 Apr 2026 21:55'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Don''t Forget - Toby Fox & Laura Shigihara', '01 Apr 2026 21:54'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'I''m Very Bad', '01 Apr 2026 21:54'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'The Door', '01 Apr 2026 21:54'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'lancer', '01 Apr 2026 21:53'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'THE WORLD REVOLVING', '01 Apr 2026 21:51'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Before the Story', '01 Apr 2026 21:50'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Chaos King', '01 Apr 2026 21:48'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Scarlet Forest', '01 Apr 2026 21:46'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Rude Buster', '01 Apr 2026 21:45'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Lantern', '01 Apr 2026 21:43'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'THE HOLY', '01 Apr 2026 21:42'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Quiet Autumn', '01 Apr 2026 21:42'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', '19. Scarlet Forest', '01 Apr 2026 21:41'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', '8. The Legend - Toby Fox', '01 Apr 2026 21:40'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', '28. Hip Shop - Toby Fox', '01 Apr 2026 21:39'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', '13. Field of Hopes and Dreams - Toby Fox', '01 Apr 2026 21:36'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Frizk - Samplerate', '01 Apr 2026 21:34'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Frizk - Samplerate', '01 Apr 2026 21:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Oh Yeah?', '01 Apr 2026 21:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '01 Apr 2026 21:28'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Frizk - Frizk Fundamentals!', '01 Apr 2026 21:26'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '01 Apr 2026 21:21'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Frizk - Soft Chords', '01 Apr 2026 21:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Friend', '01 Apr 2026 21:15'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Oh Yeah?', '01 Apr 2026 21:13'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Frizk - By The Trees', '01 Apr 2026 21:10'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bossa Break!', '01 Apr 2026 21:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Hour Funk', '01 Apr 2026 21:05'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '01 Apr 2026 14:50'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '01 Apr 2026 14:48'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '01 Apr 2026 14:36'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '01 Apr 2026 14:33'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '01 Apr 2026 14:31'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '01 Apr 2026 14:28'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '01 Apr 2026 14:25'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '01 Apr 2026 14:23'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '01 Apr 2026 14:21'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '01 Apr 2026 14:19'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '01 Apr 2026 14:17'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Petiatil Cx Htdui', '01 Apr 2026 14:16'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '01 Apr 2026 14:13'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '01 Apr 2026 14:06'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '01 Apr 2026 14:04'::timestamp),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', 'LCONDATRACK - HERE WE GO AGAIN', '01 Apr 2026 14:02'::timestamp),
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '01 Apr 2026 14:00'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Die Sterne', '01 Apr 2026 13:57'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '01 Apr 2026 13:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '01 Apr 2026 13:52'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '01 Apr 2026 13:47'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '01 Apr 2026 13:44'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '31 Mar 2026 22:04'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '31 Mar 2026 22:01'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '31 Mar 2026 21:59'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '31 Mar 2026 21:56'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '31 Mar 2026 21:53'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '31 Mar 2026 21:50'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '31 Mar 2026 21:46'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '31 Mar 2026 21:43'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '31 Mar 2026 21:41'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '31 Mar 2026 21:39'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '31 Mar 2026 21:36'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '31 Mar 2026 21:33'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '31 Mar 2026 21:31'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '31 Mar 2026 21:28'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '31 Mar 2026 21:27'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman asteria - BLOODBATH', '31 Mar 2026 20:52'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Faster N Harder', '31 Mar 2026 20:42'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Save Me', '31 Mar 2026 20:37'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '31 Mar 2026 20:17'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '31 Mar 2026 20:16'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '31 Mar 2026 20:15'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bossa Break!', '31 Mar 2026 20:09'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '31 Mar 2026 20:06'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '31 Mar 2026 20:06'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '31 Mar 2026 19:14'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i can not find my jacket', '31 Mar 2026 19:12'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'as the days go by', '31 Mar 2026 19:11'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '31 Mar 2026 19:09'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the end of clear ice', '31 Mar 2026 19:06'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what? huh? excuse me? hello???', '31 Mar 2026 19:04'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'gas station six pm', '31 Mar 2026 19:02'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i wish that i learned how to draw so i could be making things that look nice instead of this', '31 Mar 2026 19:01'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'labyrinth', '31 Mar 2026 18:57'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'drift', '31 Mar 2026 18:55'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'shiver', '31 Mar 2026 18:53'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'as the days go by', '31 Mar 2026 18:49'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'as the days go by', '31 Mar 2026 18:17'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'in and of itself', '31 Mar 2026 18:15'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '31 Mar 2026 18:12'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i can not find my jacket', '31 Mar 2026 18:10'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'fifty thousand ones and zeroes', '31 Mar 2026 18:09'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'fifty thousand ones and zeroes', '31 Mar 2026 16:20'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'labyrinth', '31 Mar 2026 16:18'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'gas station six pm', '31 Mar 2026 16:16'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i wish that i learned how to draw so i could be making things that look nice instead of this', '31 Mar 2026 16:13'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what? huh? excuse me? hello???', '31 Mar 2026 16:12'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '31 Mar 2026 16:10'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the end of clear ice', '31 Mar 2026 16:07'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '30 Mar 2026 21:09'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Descended', '30 Mar 2026 21:07'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy', '30 Mar 2026 21:05'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Let Me Go', '30 Mar 2026 21:02'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'At heart', '29 Mar 2026 18:33'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '29 Mar 2026 18:31'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'High', '29 Mar 2026 18:28'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'INSURRECTION OF THE MIND', '29 Mar 2026 18:25'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '29 Mar 2026 18:21'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Prayer', '29 Mar 2026 18:18'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Descended', '29 Mar 2026 18:15'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy', '29 Mar 2026 18:11'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '29 Mar 2026 18:09'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'At heart', '29 Mar 2026 18:04'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'High', '29 Mar 2026 18:02'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Let Me Go', '29 Mar 2026 17:58'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Descended', '29 Mar 2026 17:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '29 Mar 2026 17:51'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'INSURRECTION OF THE MIND', '29 Mar 2026 17:48'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Prayer', '29 Mar 2026 17:45'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '29 Mar 2026 17:42'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy', '29 Mar 2026 17:38'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'High', '29 Mar 2026 17:36'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'At heart', '29 Mar 2026 17:31'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', '3/31', '29 Mar 2026 17:30'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'it''s ok', '29 Mar 2026 17:29'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'her body my cathedral', '29 Mar 2026 17:25'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'tearing meat', '29 Mar 2026 17:23'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'choke it out!', '29 Mar 2026 17:21'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '29 Mar 2026 17:03'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '29 Mar 2026 17:00'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '29 Mar 2026 16:58'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '29 Mar 2026 16:56'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '29 Mar 2026 16:55'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '29 Mar 2026 16:52'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Blazing in the Dark', '29 Mar 2026 16:47'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '29 Mar 2026 16:45'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '29 Mar 2026 16:43'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '29 Mar 2026 16:42'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '29 Mar 2026 16:39'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '29 Mar 2026 16:36'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '29 Mar 2026 16:33'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '29 Mar 2026 16:32'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '29 Mar 2026 13:42'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '29 Mar 2026 13:40'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '29 Mar 2026 13:37'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '29 Mar 2026 13:35'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '29 Mar 2026 13:32'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '29 Mar 2026 13:30'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '29 Mar 2026 13:27'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '29 Mar 2026 13:26'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'choke it out!', '28 Mar 2026 23:21'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '28 Mar 2026 23:12'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '28 Mar 2026 23:09'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '28 Mar 2026 23:06'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '28 Mar 2026 23:03'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Blazing in the Dark', '28 Mar 2026 23:01'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '28 Mar 2026 22:59'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '28 Mar 2026 22:55'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '28 Mar 2026 22:53'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '28 Mar 2026 22:50'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '28 Mar 2026 22:46'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '28 Mar 2026 22:46'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '28 Mar 2026 22:41'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '28 Mar 2026 22:39'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '28 Mar 2026 22:37'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '28 Mar 2026 22:33'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '28 Mar 2026 22:13'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '28 Mar 2026 22:10'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Petiatil Cx Htdui', '28 Mar 2026 22:09'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '28 Mar 2026 22:08'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '28 Mar 2026 22:05'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '28 Mar 2026 22:03'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '28 Mar 2026 21:43'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '28 Mar 2026 21:40'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
