-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:11'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'METALLIC MADNESS (BAD FUTURE)', '22 May 2026 22:07'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'the music that plays in my dumb little critter brain', '22 May 2026 22:06'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EAT UR GUTZ!!!', '22 May 2026 22:04'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SILLY PUPPY!', '22 May 2026 22:01'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'retroslop!', '22 May 2026 22:00'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'kindanervous (>~<)', '22 May 2026 21:58'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SPANK YOUR LOCAL SPARKLEWOLF!', '22 May 2026 21:56'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'FRUTIGER ANGEL!', '22 May 2026 21:54'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'HAHAHAHAHAHAHAHAHAHA', '22 May 2026 21:52'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'MADE WITH HONEY', '22 May 2026 21:45'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'not programmed to love', '22 May 2026 21:42'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'TUG ON MY LEASH!', '22 May 2026 21:41'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'METALLIC MADNESS (BAD FUTURE)', '22 May 2026 21:39'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'RIP UR FKN PAWS OFF!', '22 May 2026 21:37'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU THINK YOU CAN WIN WITH THAT BOARD?!', '22 May 2026 21:36'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU THINK YOU CAN WIN WITH THAT BOARD?!', '22 May 2026 15:54'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'OFF THE LEASH!', '22 May 2026 15:51'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'MARBLE HORNETS', '22 May 2026 15:48'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WHIMPER FOR ME', '22 May 2026 15:47'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'retroslop!', '22 May 2026 15:46'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'FRUTIGER ANGEL!', '22 May 2026 15:43'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'kindanervous (>~<)', '22 May 2026 15:41'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'HAHAHAHAHAHAHAHAHAHA', '22 May 2026 15:40'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'the music that plays in my dumb little critter brain', '22 May 2026 15:38'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SPANK YOUR LOCAL SPARKLEWOLF!', '22 May 2026 15:36'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SILLY PUPPY!', '22 May 2026 15:33'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EAT UR GUTZ!!!', '22 May 2026 15:31'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '21 May 2026 22:07'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '21 May 2026 22:04'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '21 May 2026 22:02'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '21 May 2026 22:01'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '21 May 2026 21:59'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '21 May 2026 21:56'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '21 May 2026 21:54'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '21 May 2026 21:51'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '21 May 2026 21:50'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '21 May 2026 21:46'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '21 May 2026 21:43'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '21 May 2026 21:42'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '21 May 2026 21:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '21 May 2026 21:38'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '21 May 2026 15:52'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '21 May 2026 15:47'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '21 May 2026 15:44'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '21 May 2026 15:41'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '21 May 2026 15:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '21 May 2026 15:37'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '21 May 2026 15:35'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '21 May 2026 15:34'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '21 May 2026 15:31'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '21 May 2026 14:27'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '21 May 2026 14:24'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '21 May 2026 14:21'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '21 May 2026 14:18'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '21 May 2026 14:17'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '21 May 2026 14:15'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '21 May 2026 14:14'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '21 May 2026 14:10'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '21 May 2026 14:07'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '21 May 2026 14:02'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '21 May 2026 14:00'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '21 May 2026 13:56'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '20 May 2026 23:55'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '20 May 2026 22:09'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '20 May 2026 22:06'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '20 May 2026 22:03'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '20 May 2026 22:02'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '20 May 2026 21:58'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '20 May 2026 21:56'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '20 May 2026 21:52'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '20 May 2026 21:51'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'everybody hates shitfart666', '20 May 2026 21:51'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'teamkill (w/ kaj strife)', '20 May 2026 21:48'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'bogos binted (w/ 2a03fox & kaj strife)', '20 May 2026 21:45'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'attitude', '20 May 2026 21:44'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'borkycore (w/ kaj strife)', '20 May 2026 21:42'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'shitfart666 (w/ kaj strife)', '20 May 2026 21:40'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '19 May 2026 22:04'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '19 May 2026 22:01'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '19 May 2026 21:58'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '19 May 2026 21:56'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '19 May 2026 21:49'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '19 May 2026 18:08'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '18 May 2026 22:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'camp hill PA', '18 May 2026 21:58'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '18 May 2026 21:55'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '18 May 2026 21:53'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '18 May 2026 21:50'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '18 May 2026 21:45'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '18 May 2026 21:41'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '18 May 2026 21:38'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'RIP UR FKN PAWS OFF!', '18 May 2026 21:37'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SPANK YOUR LOCAL SPARKLEWOLF!', '18 May 2026 21:36'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'METALLIC MADNESS (BAD FUTURE)', '18 May 2026 21:25'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EAT UR GUTZ!!!', '18 May 2026 21:23'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU THINK YOU CAN WIN WITH THAT BOARD?!', '18 May 2026 21:19'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'FRUTIGER ANGEL!', '18 May 2026 21:17'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'retroslop!', '18 May 2026 21:15'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'not programmed to love', '18 May 2026 21:13'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'OFF THE LEASH!', '18 May 2026 21:09'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'rainbowz x3!!!', '17 May 2026 19:04'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'thirsty (lipsync test)', '17 May 2026 18:56'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'torção', '17 May 2026 18:55'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ondas', '17 May 2026 18:52'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'BGM for an Game that Doesn''t Exists (Full EP)', '17 May 2026 18:52'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'ANTONYMPH!', '17 May 2026 18:49'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'RAISED THRU THE INTERNET!', '17 May 2026 18:45'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'DOKTORSPIELE 4 SPARKLEFURS!!!', '17 May 2026 18:41'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'overthinking', '17 May 2026 18:31'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderfulcore', '17 May 2026 18:27'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappearing until i feel better', '17 May 2026 18:25'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'illusion of control', '17 May 2026 18:22'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'kittens', '17 May 2026 18:19'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', '143 ways to lose urself', '17 May 2026 18:18'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'they called me Violet', '17 May 2026 18:14'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'inhuman', '17 May 2026 18:12'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'just leave me to bleed', '17 May 2026 18:09'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'pls tell me what is ur dream', '17 May 2026 18:05'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'just leave me to bleed', '17 May 2026 18:04'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'The Sky Is Purple', '17 May 2026 18:03'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Pink Skirts Are Really Sweet', '17 May 2026 17:59'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Parking Stress', '17 May 2026 17:58'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'IN THE FINAL CUT', '17 May 2026 17:57'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'ITS THEME', '17 May 2026 17:53'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'GLITTER IS LOST! IT NEEDS UR HELP!', '17 May 2026 17:49'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'LOUD AND GLITTERY (JUST HOW YOU LIKE IT)', '17 May 2026 17:47'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WAG UR TAIL 2 THIS! (PAWS UP ON THE DANCEFLOOR!)', '17 May 2026 17:44'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'CUTE SPARKLE GLITTER BREAK!!!', '17 May 2026 17:36'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'PEACE AMIDST THE CHAOS', '17 May 2026 17:33'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'GL1773R ERROR CRASH LOG', '17 May 2026 17:32'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WORTH IT ALL', '17 May 2026 17:29'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '17 May 2026 14:39'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '17 May 2026 14:36'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '17 May 2026 14:33'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'camp hill PA', '17 May 2026 14:31'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '17 May 2026 14:23'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '17 May 2026 14:17'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '17 May 2026 14:12'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '17 May 2026 14:10'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '17 May 2026 14:06'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Roommate', '17 May 2026 14:05'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Would You?', '17 May 2026 14:05'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Ammateur', '17 May 2026 14:05'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Would You?', '17 May 2026 14:04'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '17 May 2026 14:03'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '17 May 2026 14:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '17 May 2026 13:57'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '17 May 2026 13:55'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '17 May 2026 13:47'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'camp hill PA', '17 May 2026 13:45'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '17 May 2026 13:43'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '16 May 2026 20:09'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '16 May 2026 20:04'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '16 May 2026 20:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '16 May 2026 19:58'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '16 May 2026 19:40'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '16 May 2026 19:37'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'OFF THE LEASH!', '16 May 2026 19:34'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WHIMPER FOR ME', '16 May 2026 19:32'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'the music that plays in my dumb little critter brain', '16 May 2026 19:30'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'METALLIC MADNESS (BAD FUTURE)', '16 May 2026 19:28'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'MARBLE HORNETS', '16 May 2026 19:24'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'HAHAHAHAHAHAHAHAHAHA', '16 May 2026 19:22'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'kindanervous (>~<)', '16 May 2026 19:18'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EAT UR GUTZ!!!', '16 May 2026 19:16'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'MADE WITH HONEY', '16 May 2026 19:13'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'RIP UR FKN PAWS OFF!', '15 May 2026 15:34'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU THINK YOU CAN WIN WITH THAT BOARD?!', '15 May 2026 15:31'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'not programmed to love', '15 May 2026 15:29'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'retroslop!', '15 May 2026 15:27'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'OFF THE LEASH!', '15 May 2026 15:24'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SILLY PUPPY!', '15 May 2026 15:19'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'the music that plays in my dumb little critter brain', '15 May 2026 15:17'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WHIMPER FOR ME', '15 May 2026 15:14'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SPANK YOUR LOCAL SPARKLEWOLF!', '15 May 2026 15:12'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'FRUTIGER ANGEL!', '15 May 2026 15:09'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'TUG ON MY LEASH!', '15 May 2026 15:07'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '15 May 2026 15:06'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '15 May 2026 15:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '15 May 2026 14:55'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '(intro)', '15 May 2026 14:55'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '15 May 2026 14:50'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '15 May 2026 14:47'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '(cassette flip)', '15 May 2026 14:47'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'camp hill PA', '15 May 2026 14:45'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '15 May 2026 14:40'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '15 May 2026 14:37'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '15 May 2026 14:34'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '15 May 2026 14:32'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '15 May 2026 14:28'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '15 May 2026 14:25'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '15 May 2026 14:11'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '15 May 2026 14:11'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'MP40 (Rawlin'' Mix)', '15 May 2026 14:10'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Meteor feat. Meeno Wave', '15 May 2026 14:05'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Blowing My Mind', '15 May 2026 14:03'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Turn Up feat. Andy Pls', '15 May 2026 14:01'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Go With The Flow', '15 May 2026 13:58'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Sienteme Estoy Aqui', '15 May 2026 13:55'::timestamp),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', 'Rejected', '15 May 2026 01:04'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'crunch bunch car crash', '13 May 2026 21:54'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'betty boothroyd''s holiday dancer', '13 May 2026 21:49'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'you''re just being weird for the sake of it.', '13 May 2026 21:47'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '13 May 2026 21:42'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'woah! (watch the paintwork)', '13 May 2026 21:40'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'The Art of War', '13 May 2026 21:39'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Dapper Cadaver', '13 May 2026 21:38'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'It Hates Me So Much', '13 May 2026 21:35'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'b-b-BASS DOWN LOW', '12 May 2026 22:06'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'FLY WITH ME', '12 May 2026 22:03'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Evil Music For BAD DOGS', '12 May 2026 22:01'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '12 May 2026 21:56'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'taste of blood (w/ Sabuze)', '12 May 2026 21:54'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'kittens', '12 May 2026 21:52'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappearing until i feel better', '12 May 2026 21:49'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'overthinking', '12 May 2026 21:46'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'limited in love (w/ AKIBA)', '12 May 2026 21:44'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'pls tell me what is ur dream (w/ Eden FM)', '12 May 2026 21:40'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'illusion of control (w/ Iwakura)', '11 May 2026 22:03'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i want to eat ur heart couse i love u', '11 May 2026 22:01'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappearing until i feel better', '11 May 2026 21:59'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'limited in love (w/ AKIBA)', '11 May 2026 21:56'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'pls tell me what is ur dream (w/ Eden FM)', '11 May 2026 21:53'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'sorry mom i''m making breakcore xd', '11 May 2026 21:51'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'yours forever (w/ abyssal.angel)', '11 May 2026 21:49'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'Inhuman (w/ aak3)', '11 May 2026 21:47'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'you''re my friend now (w/ DXRKWRLD)', '11 May 2026 21:44'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'kittens', '11 May 2026 21:42'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'taste of blood (w/ Sabuze)', '11 May 2026 21:40'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'just leave me to bleed', '11 May 2026 21:37'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'it''s 2am i can''t sleep (/w Enkei)', '11 May 2026 21:36'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy - Winter Mix', '11 May 2026 21:35'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy - Winter Mix', '08 May 2026 22:08'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'bye', '08 May 2026 22:05'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Anxiety3', '08 May 2026 22:02'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '08 May 2026 21:59'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Never', '08 May 2026 21:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy - Winter Mix', '08 May 2026 21:52'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'bye', '08 May 2026 21:49'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '08 May 2026 21:45'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '08 May 2026 21:41'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '08 May 2026 21:37'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'yours forever (w/ abyssal.angel)', '08 May 2026 15:58'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '08 May 2026 15:54'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'illusion of control (w/ Iwakura)', '08 May 2026 15:52'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'taste of blood (w/ Sabuze)', '08 May 2026 15:50'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '08 May 2026 15:48'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'total jealous void', '08 May 2026 15:45'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'tired of myself', '08 May 2026 15:40'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappear like everyone else', '08 May 2026 15:38'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', '143 ways to lose urself', '08 May 2026 15:36'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'Inhuman (w/ aak3)', '08 May 2026 15:34'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappearing until i feel better', '08 May 2026 15:32'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappearing until i feel better', '07 May 2026 22:04'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'problem after problem and over and over', '07 May 2026 22:01'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wake up Violet', '07 May 2026 21:59'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'overthinking', '07 May 2026 21:55'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'usedcvnt abyssal.angel - yours forever', '07 May 2026 21:52'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '07 May 2026 21:50'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '07 May 2026 21:47'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '07 May 2026 21:42'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '07 May 2026 21:37'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'woah! (watch the paintwork)', '07 May 2026 21:36'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'you''re just being weird for the sake of it.', '07 May 2026 21:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '07 May 2026 15:51'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '07 May 2026 15:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '07 May 2026 15:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '07 May 2026 15:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '07 May 2026 15:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '06 May 2026 22:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '06 May 2026 22:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby (Intermission)', '06 May 2026 22:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '06 May 2026 21:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '06 May 2026 21:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '06 May 2026 21:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '06 May 2026 21:53'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '06 May 2026 14:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '06 May 2026 14:14'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '06 May 2026 14:12'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '06 May 2026 14:10'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby (Intermission)', '06 May 2026 14:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '06 May 2026 14:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '06 May 2026 14:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '06 May 2026 14:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '05 May 2026 22:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '05 May 2026 22:03'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'illusion of control (w/ Iwakura)', '05 May 2026 22:01'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'yours forever (w/ abyssal.angel)', '05 May 2026 21:58'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'sorry mom i''m making breakcore xd', '05 May 2026 21:56'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'overthinking', '05 May 2026 21:52'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', '143 ways to lose urself', '05 May 2026 21:50'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'pls tell me what is ur dream (w/ Eden FM)', '05 May 2026 21:46'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'you''re my friend now (w/ DXRKWRLD)', '05 May 2026 21:44'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'taste of blood (w/ Sabuze)', '05 May 2026 21:42'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Mix Soda (Bonus Track)', '04 May 2026 22:07'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Cream Soda!', '04 May 2026 22:05'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'THE DAWN', '04 May 2026 22:00'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bubble Bobble!', '04 May 2026 21:57'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Overdosed (Anxiety)', '04 May 2026 21:52'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Mix Soda (Bonus Track)', '04 May 2026 21:49'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'THE DAWN', '04 May 2026 21:44'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bubble Bobble!', '04 May 2026 21:42'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Cream Soda!', '04 May 2026 21:39'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Overdosed (Anxiety)', '04 May 2026 15:46'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'epicenter of happiness', '30 Apr 2026 22:09'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'antidote', '30 Apr 2026 22:05'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'a tear at eventide (w/ Bendel)', '30 Apr 2026 22:03'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'total jealous void', '30 Apr 2026 22:00'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'tired of myself', '30 Apr 2026 21:56'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'rumination', '30 Apr 2026 21:52'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '30 Apr 2026 21:48'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'antidote', '30 Apr 2026 21:45'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'epicenter of happiness', '30 Apr 2026 21:41'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'aesthetics of self-destruction', '30 Apr 2026 21:39'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'it will be cloudy forever', '30 Apr 2026 21:38'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'it will be cloudy forever', '30 Apr 2026 15:49'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'tired of myself', '30 Apr 2026 15:45'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'total jealous void', '30 Apr 2026 15:42'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'rumination', '30 Apr 2026 15:37'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'a tear at eventide (w/ Bendel)', '30 Apr 2026 15:35'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'aesthetics of self-destruction', '30 Apr 2026 15:32'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'first love theory', '30 Apr 2026 15:28'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'antidote', '29 Apr 2026 22:02'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'epicenter of happiness', '29 Apr 2026 21:59'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'HERE FOR A GOOD TIME NOT A LONG TIME', '29 Apr 2026 21:56'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'FLY WITH ME', '29 Apr 2026 21:53'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'IN DA DOGHOUSE', '29 Apr 2026 21:51'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'EAT YOU UP', '29 Apr 2026 21:49'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Just Be Competent', '29 Apr 2026 21:46'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Evil Music For BAD DOGS', '29 Apr 2026 21:44'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'HERE FOR A GOOD TIME NOT A LONG TIME', '29 Apr 2026 21:41'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'b-b-BASS DOWN LOW', '29 Apr 2026 21:39'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'FLY WITH ME', '29 Apr 2026 21:37'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'HERE FOR A GOOD TIME NOT A LONG TIME', '29 Apr 2026 21:34'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Evil Music For BAD DOGS', '29 Apr 2026 21:32'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MY DOG RUNS ON SOYLENT', '29 Apr 2026 19:39'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '29 Apr 2026 19:38'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '29 Apr 2026 19:21'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '29 Apr 2026 19:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '29 Apr 2026 15:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '28 Apr 2026 18:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '28 Apr 2026 18:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '27 Apr 2026 22:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby (Intermission)', '27 Apr 2026 22:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '27 Apr 2026 21:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '27 Apr 2026 21:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '27 Apr 2026 21:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '27 Apr 2026 21:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '27 Apr 2026 21:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '27 Apr 2026 21:47'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '27 Apr 2026 21:42'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'stop me if you''ve heard this one.', '27 Apr 2026 21:40'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '27 Apr 2026 21:36'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'crunch bunch car crash', '27 Apr 2026 18:04'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '27 Apr 2026 18:00'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'woah! (watch the paintwork)', '27 Apr 2026 17:59'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'stop me if you''ve heard this one.', '27 Apr 2026 17:56'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '27 Apr 2026 17:51'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '27 Apr 2026 17:50'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'crunch bunch car crash', '27 Apr 2026 17:47'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'total fucking stabbage', '27 Apr 2026 14:13'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '27 Apr 2026 14:08'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'woah! (watch the paintwork)', '27 Apr 2026 14:07'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'betty boothroyd''s holiday dancer', '27 Apr 2026 14:04'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'the eternal march of the bastard squad', '27 Apr 2026 14:02'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '27 Apr 2026 13:58'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'you''re just being weird for the sake of it.', '27 Apr 2026 13:55'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'all''s well that ends well', '27 Apr 2026 13:54'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '27 Apr 2026 13:50'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'stop me if you''ve heard this one.', '27 Apr 2026 13:46'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'woah! (watch the paintwork)', '26 Apr 2026 18:58'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'crunch bunch car crash', '26 Apr 2026 18:55'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', '(still) too young', '26 Apr 2026 18:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '23 Apr 2026 22:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '23 Apr 2026 22:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '23 Apr 2026 22:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '23 Apr 2026 22:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '23 Apr 2026 22:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '23 Apr 2026 22:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '23 Apr 2026 21:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '23 Apr 2026 21:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '23 Apr 2026 21:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '23 Apr 2026 21:53'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '23 Apr 2026 21:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '23 Apr 2026 21:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '23 Apr 2026 21:48'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '23 Apr 2026 21:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '23 Apr 2026 21:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '23 Apr 2026 21:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '23 Apr 2026 21:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '23 Apr 2026 21:39'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '23 Apr 2026 21:37'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'betty boothroyd''s holiday dancer', '23 Apr 2026 21:35'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'too young', '23 Apr 2026 19:14'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'all''s well that ends well', '23 Apr 2026 19:13'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '23 Apr 2026 18:12'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '23 Apr 2026 18:10'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '23 Apr 2026 18:09'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'new notification dopamine', '23 Apr 2026 18:08'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
