-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('goreshit — Singles & Sessions', 'goreshit', 'crunch bunch car crash', '22 Apr 2026 21:51'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'banfield''s crazy fingers', '22 Apr 2026 21:47'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'stop me if you''ve heard this one.', '22 Apr 2026 21:45'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'betty boothroyd''s holiday dancer', '22 Apr 2026 21:42'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '22 Apr 2026 21:38'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'the eternal march of the bastard squad', '22 Apr 2026 21:35'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'you''re just being weird for the sake of it.', '22 Apr 2026 21:34'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '22 Apr 2026 21:33'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '22 Apr 2026 19:26'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'supa girl racer 5', '22 Apr 2026 19:23'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nothing makes sense and i''m lost', '22 Apr 2026 19:21'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'feeling lucky', '22 Apr 2026 19:20'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Hunderprest', '22 Apr 2026 19:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '22 Apr 2026 18:53'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '22 Apr 2026 17:36'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '22 Apr 2026 17:33'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '22 Apr 2026 17:30'::timestamp),
  ('hkmori — Singles & Sessions', 'hkmori', '0xff', '22 Apr 2026 17:30'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '22 Apr 2026 16:50'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '22 Apr 2026 16:48'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Blazing in the Dark', '22 Apr 2026 16:46'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '22 Apr 2026 16:41'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '22 Apr 2026 16:39'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '22 Apr 2026 16:37'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '22 Apr 2026 16:35'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '22 Apr 2026 16:32'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '22 Apr 2026 16:28'::timestamp),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', 'IX FALL$ - buried yet so frail', '22 Apr 2026 16:26'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '22 Apr 2026 16:23'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'your eyes', '22 Apr 2026 16:21'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '22 Apr 2026 16:20'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'FINAL CAT MEOW ULTIMATE', '22 Apr 2026 16:17'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wake up Violet', '22 Apr 2026 16:15'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderful ending see u later', '22 Apr 2026 16:11'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderfulcore', '22 Apr 2026 16:08'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '22 Apr 2026 16:07'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '22 Apr 2026 16:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '22 Apr 2026 15:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '22 Apr 2026 15:45'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'gali.9221', '20 Apr 2026 21:19'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'SWEET NOISES', '20 Apr 2026 21:17'::timestamp),
  ('theSpackster — Singles & Sessions', 'theSpackster', 'RK9', '20 Apr 2026 21:00'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'ritual rave', '19 Apr 2026 13:51'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Coronach', '19 Apr 2026 13:42'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Kinchyle', '19 Apr 2026 13:38'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Sculptor''s Cave', '19 Apr 2026 13:33'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Tous Les Jours', '19 Apr 2026 13:32'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Mastodon Matador', '19 Apr 2026 13:31'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'What Went Weird', '19 Apr 2026 13:30'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Near Death Bossa Nova', '19 Apr 2026 13:29'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Near Death Bossa Nova', '19 Apr 2026 13:28'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Near Death Bossa Nova', '19 Apr 2026 13:27'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Bad at Texting / World''s Last Mango Juul Pod', '19 Apr 2026 13:26'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Introductory Remarks', '19 Apr 2026 13:24'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Blink Blink Blink', '19 Apr 2026 13:24'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Kelly''s Dungeon', '19 Apr 2026 13:22'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Hypemanda Mk I', '19 Apr 2026 13:21'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'black tar heroin', '19 Apr 2026 13:21'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'rock that microphone', '19 Apr 2026 13:19'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'LONG LIVE THE KING', '19 Apr 2026 13:18'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '19 Apr 2026 13:16'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '19 Apr 2026 13:13'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '19 Apr 2026 13:11'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '19 Apr 2026 13:11'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '19 Apr 2026 13:09'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '19 Apr 2026 13:08'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'NAH DAS SOKETHING EVIL;', '19 Apr 2026 13:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '19 Apr 2026 13:03'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderful ending see u later', '19 Apr 2026 01:10'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'disappear like everyone else', '19 Apr 2026 01:07'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '19 Apr 2026 01:05'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'problem after problem and over and over', '19 Apr 2026 01:02'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wake up Violet', '19 Apr 2026 00:59'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderfulcore', '19 Apr 2026 00:56'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderful ending see u later', '19 Apr 2026 00:53'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '19 Apr 2026 00:50'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Never', '19 Apr 2026 00:43'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '19 Apr 2026 00:40'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Anxiety3', '17 Apr 2026 22:10'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '17 Apr 2026 22:07'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Never', '17 Apr 2026 22:03'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'bye', '17 Apr 2026 22:01'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Anxiety3', '17 Apr 2026 21:58'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy - Winter Mix', '17 Apr 2026 21:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '17 Apr 2026 21:52'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '17 Apr 2026 21:49'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'OK Go Crazy - Winter Mix', '17 Apr 2026 21:48'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'bye', '17 Apr 2026 21:45'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Anxiety3', '17 Apr 2026 21:42'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Never', '17 Apr 2026 21:38'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '17 Apr 2026 21:38'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'PUPLIFE', '17 Apr 2026 20:06'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderful ending see u later', '17 Apr 2026 20:05'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'problem after problem and over and over', '17 Apr 2026 20:04'::timestamp),
  ('theSpackster — Singles & Sessions', 'theSpackster', 'camelCase', '17 Apr 2026 20:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '16 Apr 2026 17:35'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '16 Apr 2026 17:33'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '16 Apr 2026 17:26'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '16 Apr 2026 17:23'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '16 Apr 2026 17:22'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '16 Apr 2026 17:20'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '16 Apr 2026 17:17'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '16 Apr 2026 17:14'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '16 Apr 2026 17:12'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '16 Apr 2026 17:10'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '16 Apr 2026 17:07'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '16 Apr 2026 17:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '16 Apr 2026 17:04'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '16 Apr 2026 17:02'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '16 Apr 2026 16:58'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '16 Apr 2026 16:56'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '16 Apr 2026 16:54'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '16 Apr 2026 16:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '16 Apr 2026 16:50'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '16 Apr 2026 16:48'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '16 Apr 2026 16:45'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '16 Apr 2026 16:43'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '16 Apr 2026 16:40'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '16 Apr 2026 16:38'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '16 Apr 2026 16:36'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '16 Apr 2026 16:34'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '16 Apr 2026 16:32'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '16 Apr 2026 16:28'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '16 Apr 2026 16:27'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '16 Apr 2026 16:22'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '16 Apr 2026 16:21'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '16 Apr 2026 16:21'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'wonderful ending see u later', '16 Apr 2026 16:19'::timestamp),
  ('theSpackster — Singles & Sessions', 'theSpackster', 'Nightlight Interlude', '16 Apr 2026 16:17'::timestamp),
  ('theSpackster — Singles & Sessions', 'theSpackster', 'POP! THAT! POOLTOY!', '16 Apr 2026 16:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 22:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 22:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 22:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 22:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 22:13'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 22:11'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '15 Apr 2026 22:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 22:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 22:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 22:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 21:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 21:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 21:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 21:52'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Pinata Break', '15 Apr 2026 21:49'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Love Zombie', '15 Apr 2026 21:46'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Beep Beep Bag', '15 Apr 2026 21:44'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'BrainSick', '15 Apr 2026 21:42'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Bad at Texting / World''s Last Mango Juul Pod', '15 Apr 2026 20:37'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'non violent reoccurance', '15 Apr 2026 20:05'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'fake icarus', '15 Apr 2026 20:04'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'gali.9221', '15 Apr 2026 20:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '15 Apr 2026 19:56'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '15 Apr 2026 19:53'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '15 Apr 2026 19:51'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '15 Apr 2026 19:49'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '15 Apr 2026 19:46'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '15 Apr 2026 19:44'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '15 Apr 2026 19:41'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '15 Apr 2026 19:34'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '15 Apr 2026 19:32'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '15 Apr 2026 19:30'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '15 Apr 2026 19:28'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '15 Apr 2026 19:25'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '15 Apr 2026 19:23'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SOLVEIG', '15 Apr 2026 19:20'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '15 Apr 2026 19:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 15:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 15:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 15:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '15 Apr 2026 15:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 15:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 15:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 15:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 15:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 15:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 15:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 15:13'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 15:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 15:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '15 Apr 2026 15:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 14:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 14:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 14:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 14:51'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 14:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 14:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 14:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '15 Apr 2026 14:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 14:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 14:34'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 14:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 14:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 14:21'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 14:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 14:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 14:14'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 14:11'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '15 Apr 2026 14:09'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '15 Apr 2026 14:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '15 Apr 2026 14:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '15 Apr 2026 14:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '15 Apr 2026 13:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '15 Apr 2026 13:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '15 Apr 2026 13:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '15 Apr 2026 13:52'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Tous Les Jours', '14 Apr 2026 22:05'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Snaggle Tooth', '14 Apr 2026 22:04'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Sweet Thing', '14 Apr 2026 22:02'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Do You Have Cowboy Hat', '14 Apr 2026 22:01'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Threat Level Midnight', '14 Apr 2026 22:00'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Edwin Rosen - Vertigo', '14 Apr 2026 21:55'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Die Sonne in deinem Zimmer', '14 Apr 2026 21:52'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Edwin Rosen - 21 Nächte wach', '14 Apr 2026 21:50'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'kontrollverlust', '14 Apr 2026 21:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '14 Apr 2026 21:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 21:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 21:40'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 21:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '14 Apr 2026 21:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '14 Apr 2026 21:34'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 21:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 21:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 21:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 21:24'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '14 Apr 2026 21:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '14 Apr 2026 21:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 21:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '14 Apr 2026 21:15'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '14 Apr 2026 21:13'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 21:10'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 21:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 21:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '14 Apr 2026 21:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '14 Apr 2026 21:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 20:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '14 Apr 2026 20:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 20:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '14 Apr 2026 20:51'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 20:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '14 Apr 2026 20:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '14 Apr 2026 20:46'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 20:44'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 20:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 20:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 20:36'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 19:11'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '14 Apr 2026 19:09'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 19:07'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 19:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '14 Apr 2026 19:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 19:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'give it a little more', '14 Apr 2026 18:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Beach Nearby', '14 Apr 2026 18:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '14 Apr 2026 18:53'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 18:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 18:48'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '14 Apr 2026 17:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Wish It Were Colder', '14 Apr 2026 17:26'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Blue Raspberry Field', '14 Apr 2026 17:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '14 Apr 2026 17:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'By The Trees', '14 Apr 2026 17:19'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '14 Apr 2026 17:17'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Sculptor''s Cave', '14 Apr 2026 17:16'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Kinchyle', '14 Apr 2026 17:11'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Blakk Satanik Fvkkstorm', '14 Apr 2026 17:07'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'The Art of Resurrection', '14 Apr 2026 17:04'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Coronach', '14 Apr 2026 16:56'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'Hunderprest', '14 Apr 2026 16:50'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '13 Apr 2026 21:55'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re fake as fuck', '13 Apr 2026 21:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bad crack style 2012', '13 Apr 2026 21:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'terminal oden od', '13 Apr 2026 21:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '13 Apr 2026 21:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'move like a freak!', '13 Apr 2026 21:46'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'stay high', '13 Apr 2026 21:43'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'scene kweenz', '13 Apr 2026 21:41'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', '21', '13 Apr 2026 21:39'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '13 Apr 2026 21:37'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '13 Apr 2026 21:36'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '13 Apr 2026 21:35'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '13 Apr 2026 17:10'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:09'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:07'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:04'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:02'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 17:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:59'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:57'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:56'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:54'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:50'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:49'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:47'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:45'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '13 Apr 2026 16:44'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PROTECC ATTACC SEXYBACC', '13 Apr 2026 16:42'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'death of the candy raver', '13 Apr 2026 16:39'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'stop me if you''ve heard this one.', '13 Apr 2026 16:37'::timestamp),
  ('goreshit — Singles & Sessions', 'goreshit', 'too young', '13 Apr 2026 16:36'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Mercenary Park', '13 Apr 2026 15:38'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Saluting the Fallen', '13 Apr 2026 15:36'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'More Gun', '13 Apr 2026 15:33'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'The Art of War', '13 Apr 2026 15:31'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'RED Triumphs!', '13 Apr 2026 15:29'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'It Hates Me So Much', '13 Apr 2026 15:27'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Seduce Me!', '13 Apr 2026 15:26'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Dreams of Cruelty', '13 Apr 2026 15:25'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Drunken Pipe Bomb', '13 Apr 2026 15:24'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'BLU Triumphs!', '13 Apr 2026 15:22'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Three Days to Live', '13 Apr 2026 15:20'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'A Little Heart to Heart', '13 Apr 2026 15:19'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Dapper Cadaver', '13 Apr 2026 15:17'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Rocket Jump Waltz', '13 Apr 2026 15:16'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Playing With Danger', '13 Apr 2026 15:12'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Red Bread', '13 Apr 2026 15:10'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Team Fortress 2', '13 Apr 2026 15:09'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Rise of the Living Bread', '13 Apr 2026 15:07'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'MEDIC!', '13 Apr 2026 15:05'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Saxton''s Dilemma', '13 Apr 2026 15:04'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Soldier of Dance', '13 Apr 2026 15:03'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'The Calm', '13 Apr 2026 15:00'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Yeti Park', '13 Apr 2026 14:57'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Right Behind You', '13 Apr 2026 14:55'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Faster Than a Speeding Bullet', '13 Apr 2026 14:54'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Archimedes', '13 Apr 2026 14:52'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Carousel of Curses', '13 Apr 2026 14:51'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Misfortune Teller', '13 Apr 2026 14:50'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'ROBOTS!', '13 Apr 2026 14:48'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'VERY COOL', '13 Apr 2026 14:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'BUMP THE HARDSTYLE TRANCE', '13 Apr 2026 14:44'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'sharding abt hrt shit', '13 Apr 2026 14:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'remeowved something', '13 Apr 2026 14:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'wavelength of my feelings pls feel my energy', '13 Apr 2026 14:39'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'drowning timeline of the wavelength', '13 Apr 2026 14:37'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'some kinda chiller hardcore', '13 Apr 2026 14:35'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'unrefined brain activity huh', '13 Apr 2026 14:34'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'FART IN your ass not mine oplaessesese', '13 Apr 2026 14:32'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'ak-gigabab_9122', '13 Apr 2026 14:29'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepyr.tech', '13 Apr 2026 14:26'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the happenstance occurs in an unseemingly manner power withheld above all else dont think to hard', '13 Apr 2026 14:22'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'truly another track where someone pisses herself', '13 Apr 2026 14:21'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'more unknown full of it', '13 Apr 2026 14:19'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'found the feeling', '13 Apr 2026 14:17'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepicarpy.tek', '13 Apr 2026 14:16'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'hound down', '13 Apr 2026 14:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '13 Apr 2026 13:59'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Time', '12 Apr 2026 12:23'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Roommate', '12 Apr 2026 12:21'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Please select an save file', '12 Apr 2026 12:19'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Ammateur', '12 Apr 2026 12:16'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Would You?', '12 Apr 2026 12:15'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Would You?', '12 Apr 2026 12:13'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:31'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:30'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:29'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:28'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:27'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:25'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:23'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:21'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:20'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:20'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:17'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:16'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:14'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:13'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:12'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:11'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:09'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:08'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:06'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:04'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:03'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:03'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:02'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 22:59'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 22:57'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 22:56'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '10 Apr 2026 20:47'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '10 Apr 2026 20:45'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Transgender', '10 Apr 2026 20:28'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:24'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Kerosene', '10 Apr 2026 20:22'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Transgender', '10 Apr 2026 20:19'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:15'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Kerosene', '10 Apr 2026 20:12'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:11'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:07'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:03'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 19:59'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 19:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '10 Apr 2026 16:28'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '10 Apr 2026 16:05'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '10 Apr 2026 16:02'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '10 Apr 2026 15:59'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '10 Apr 2026 15:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '10 Apr 2026 15:53'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
