-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'papa hates me', '12 Jun 2026 21:57'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'aftermath', '12 Jun 2026 21:55'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'donkage', '12 Jun 2026 21:48'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'stuck-seasick', '12 Jun 2026 21:43'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'trains not making it', '12 Jun 2026 21:39'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'wandering', '12 Jun 2026 21:37'::timestamp),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', 'a lofty end', '12 Jun 2026 21:36'::timestamp),
  ('gali.inveraph//THE WELL', 'Vertigoaway', 'the well', '12 Jun 2026 21:35'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'ANTONYMPH!', '12 Jun 2026 20:57'::timestamp),
  ('gali.inveraph//THE WELL', 'Vertigoaway', 'the well', '12 Jun 2026 20:53'::timestamp),
  ('gali.inveraph//THE WELL', 'Vertigoaway', 'as as as as the springs...', '12 Jun 2026 20:51'::timestamp),
  ('gali.inveraph//THE WELL', 'Vertigoaway', 'DR GEARS', '12 Jun 2026 20:49'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'EVIL (KUZU WANTS YOU TO THINK THAT HE''S EVIL BUT HE''S REALLY JUST A SWEETHEART)', '12 Jun 2026 20:48'::timestamp),
  ('THE RETURN OF SPARKLEWOLF RADIO', 'SPARKLEWOLF RADIO', 'SPANK YOUR LOCAL SPARKLEWOLF!', '12 Jun 2026 20:45'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'THEY''RE PLAYING PIANO IN THE DARK', '12 Jun 2026 20:43'::timestamp),
  ('THE RETURN OF SPARKLEWOLF RADIO', 'SPARKLEWOLF RADIO', 'WHIMPER FOR ME', '12 Jun 2026 20:41'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'GLITTER GLITTER GLITTER', '12 Jun 2026 20:38'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'SO HAZY', '12 Jun 2026 20:35'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'PARTY LIEK ITS 2012!', '12 Jun 2026 20:32'::timestamp),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', 'CAUTION CAUTION CAUTION', '12 Jun 2026 20:30'::timestamp),
  ('THE RETURN OF SPARKLEWOLF RADIO', 'SPARKLEWOLF RADIO', 'MARBLE HORNETS', '12 Jun 2026 20:29'::timestamp),
  ('MAILPUP', 'MAILPUP', 'MY DOG RUNS ON SOYLENT', '12 Jun 2026 20:26'::timestamp),
  ('MAILPUP', 'MAILPUP', 'HEWWO! ÒwÓ', '12 Jun 2026 20:24'::timestamp),
  ('FANSERVICE', 'MAILPUP', 'HARDER DADDY', '12 Jun 2026 20:20'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '12 Jun 2026 15:57'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', '4K CARPET', '12 Jun 2026 15:55'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'FINALE', '12 Jun 2026 15:51'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'DANCE ALL NIGHT', '12 Jun 2026 15:49'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '12 Jun 2026 15:46'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'VENOMOUS', '12 Jun 2026 15:44'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'TUMMY', '12 Jun 2026 15:41'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PUPPY 4EVER', '12 Jun 2026 15:39'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '12 Jun 2026 15:36'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', '4K CARPET', '12 Jun 2026 15:34'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'FINALE', '12 Jun 2026 15:30'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'DANCE ALL NIGHT', '11 Jun 2026 15:57'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '11 Jun 2026 15:54'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'VENOMOUS', '11 Jun 2026 15:52'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'TUMMY', '11 Jun 2026 15:49'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PUPPY 4EVER', '11 Jun 2026 15:46'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '11 Jun 2026 15:44'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', '4K CARPET', '11 Jun 2026 15:42'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'FINALE', '11 Jun 2026 15:38'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'DANCE ALL NIGHT', '11 Jun 2026 15:36'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '11 Jun 2026 15:35'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '10 Jun 2026 22:05'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'VENOMOUS', '10 Jun 2026 22:03'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'TUMMY', '10 Jun 2026 22:01'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PUPPY 4EVER', '10 Jun 2026 21:58'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '10 Jun 2026 21:55'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', '4K CARPET', '10 Jun 2026 21:53'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'FINALE', '10 Jun 2026 21:50'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'DANCE ALL NIGHT', '10 Jun 2026 21:48'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '10 Jun 2026 21:44'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'VENOMOUS', '10 Jun 2026 21:42'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'TUMMY', '10 Jun 2026 21:40'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PUPPY 4EVER', '10 Jun 2026 21:37'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '10 Jun 2026 21:35'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'hound down', '10 Jun 2026 16:55'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'Lois', '10 Jun 2026 16:48'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'Lil Jon has trouble with his math test', '10 Jun 2026 16:48'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'Drum? And Bass', '10 Jun 2026 16:47'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'PREY', '10 Jun 2026 14:15'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', '4K CARPET', '10 Jun 2026 14:13'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'FINALE', '10 Jun 2026 14:10'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'DANCE ALL NIGHT', '10 Jun 2026 14:07'::timestamp),
  ('PASSENGERPRINCESS', 'passengerprincess', 'CREDIT CARD', '10 Jun 2026 14:04'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SILLY PUPPY!', '09 Jun 2026 22:00'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'old money bitch', '09 Jun 2026 21:56'::timestamp),
  ('theSpackster — Singles & Sessions', 'theSpackster', 'cookies n'' cream', '09 Jun 2026 21:44'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'Femboifoxxx', '09 Jun 2026 21:39'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'femboifoxxx (ALIXI remix)', '09 Jun 2026 17:50'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'femboifoxxx (ALIXI remix)', '09 Jun 2026 17:15'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'femboifoxxx (loud equals funny vip)', '09 Jun 2026 17:05'::timestamp),
  ('Not a Furry Album Cover', 'Betu', 'Falling Apart', '09 Jun 2026 01:03'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'old money bitch', '08 Jun 2026 22:01'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'PUPPY TF!!', '08 Jun 2026 22:00'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'Femboifoxxx', '08 Jun 2026 21:57'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'bogos binted (ft. 2a03fox & kaj strife)', '08 Jun 2026 21:54'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MTB', '08 Jun 2026 14:42'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MTB', '08 Jun 2026 14:42'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '08 Jun 2026 14:35'::timestamp),
  ('Not a Furry Album Cover', 'Betu', 'Cry On My Own', '07 Jun 2026 01:58'::timestamp),
  ('Not a Furry Album Cover', 'Betu', 'Rudy Knows', '07 Jun 2026 01:30'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'BREAK THIS THE BREAKING POINT 2 [BREAK CORPS 2]', '07 Jun 2026 01:09'::timestamp),
  ('Not a Furry Album Cover', 'Betu', 'Alone', '07 Jun 2026 00:41'::timestamp),
  ('Not a Furry Album Cover', 'Betu', 'Falling Apart', '07 Jun 2026 00:29'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Would You?', '06 Jun 2026 15:35'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'need feedback plz', '05 Jun 2026 20:23'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'The Drop', '05 Jun 2026 20:23'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', '4K CARPET (rmx)', '05 Jun 2026 20:08'::timestamp),
  ('FANSERVICE', 'MAILPUP', 'HARDER DADDY', '05 Jun 2026 19:57'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'bogos binted (ft. 2a03fox & kaj strife)', '05 Jun 2026 19:56'::timestamp),
  ('hikikomori days', 'Shoebill', 'fresh meat (remix of diet tea other cola)', '05 Jun 2026 19:53'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'Phone Sex VIP', '05 Jun 2026 01:31'::timestamp),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', 'the really fucking cool intro music from car set 2 original soundtrack', '05 Jun 2026 01:17'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'METALLIC MADNESS BAD FUTURE REMIX', '05 Jun 2026 01:11'::timestamp),
  ('621 gecs — Singles & Sessions', '621 gecs', 'GOTH BITCH DUB', '05 Jun 2026 01:10'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'wanna fucking scream!!!', '05 Jun 2026 01:04'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'NAMx (MAILPUP flip)', '03 Jun 2026 22:02'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'I REALLY REALLY REALLY HATE THE WORLD BUT THAT''S OK AT LEAST I''VE GOT MY GABBER DRUM', '03 Jun 2026 22:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '03 Jun 2026 21:59'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '03 Jun 2026 21:57'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '03 Jun 2026 21:55'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'crashed', '03 Jun 2026 21:52'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the vile spawn-aborted', '03 Jun 2026 21:50'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'a lofty end', '03 Jun 2026 21:49'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'truly another track where someone pisses herself', '03 Jun 2026 21:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the happenstance occurs in an unseemingly manner power withheld above all else dont think to hard', '03 Jun 2026 21:43'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'more unknown full of it', '03 Jun 2026 21:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'JUNGLEE SPIIT', '03 Jun 2026 21:37'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'FINAL CAT MEOW ULTIMATE', '03 Jun 2026 21:36'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'IN EFFEVT', '03 Jun 2026 19:56'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'unrefined brain activity huh', '03 Jun 2026 19:55'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'as as as as the springs...', '03 Jun 2026 19:53'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'wandering', '03 Jun 2026 19:52'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepicarpy.tek', '03 Jun 2026 19:50'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'rebenge of the sighted', '03 Jun 2026 19:48'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'nev3r_end1ng', '03 Jun 2026 19:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'nev3r_end1ng', '03 Jun 2026 18:48'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the well', '03 Jun 2026 18:46'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'remeowved something', '03 Jun 2026 18:45'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'b-b-BASS DOWN LOW (GABBER TIME)', '03 Jun 2026 18:40'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Just Be Competent', '03 Jun 2026 18:37'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'b-b-BASS DOWN LOW', '03 Jun 2026 18:35'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'Just Artist Struggles', '03 Jun 2026 18:34'::timestamp),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', 'EAT YOU UP', '03 Jun 2026 18:31'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'attitude', '03 Jun 2026 18:25'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'drowning timeline of the wavelength', '03 Jun 2026 18:24'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'BREAK THIS THE BREAKING POINT 2 [BREAK CORPS 2]', '03 Jun 2026 18:05'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'drowning timeline of the wavelength', '03 Jun 2026 17:51'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'kivkin it', '03 Jun 2026 17:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'sharding abt hrt shit', '03 Jun 2026 17:45'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'donkage', '03 Jun 2026 17:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'gali.9221', '03 Jun 2026 17:38'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'wavelength of my feelings pls feel my energy', '03 Jun 2026 17:36'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'chaotic aberration', '03 Jun 2026 17:33'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'd8imension hole', '03 Jun 2026 17:32'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'found the feeling', '03 Jun 2026 17:30'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'hexd landscape itself beats harder than a bleeding synth', '03 Jun 2026 17:28'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'DR GEARS', '03 Jun 2026 17:26'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'i never fukd a bih w a prolap', '03 Jun 2026 17:23'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'some kinda chiller hardcore', '03 Jun 2026 17:22'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'pls take ur shoes off b4 entering', '03 Jun 2026 17:18'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'DR GEARS', '03 Jun 2026 16:29'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'DR GEARS', '03 Jun 2026 15:50'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'i never fukd a bih w a prolap', '03 Jun 2026 15:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'some kinda chiller hardcore', '03 Jun 2026 15:46'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'YEAR OF THE NAUGHTY FOX', '02 Jun 2026 22:31'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'TUMMY', '02 Jun 2026 22:05'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'DANCE ALL NIGHT', '02 Jun 2026 22:03'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'PUPPY 4EVER', '02 Jun 2026 22:00'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'PREY', '02 Jun 2026 21:57'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'VENOMOUS', '02 Jun 2026 21:56'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'VENOMOUS', '02 Jun 2026 21:55'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', '4K CARPET', '02 Jun 2026 21:53'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'FINALE', '02 Jun 2026 21:49'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'CREDIT CARD', '02 Jun 2026 21:46'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'TUMMY', '02 Jun 2026 21:44'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'DANCE ALL NIGHT', '02 Jun 2026 21:41'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'PUPPY 4EVER', '02 Jun 2026 21:39'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'PREY', '02 Jun 2026 21:36'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'VENOMOUS', '02 Jun 2026 21:34'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'ADOPT AND RAISE A CUTE PET!', '02 Jun 2026 21:23'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'the music that plays in my dumb little critter brain', '02 Jun 2026 21:20'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'CARAMELLDANSEN!!!', '02 Jun 2026 21:18'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'GLITTER IS LOST! IT NEEDS UR HELP!', '02 Jun 2026 21:15'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'CUTE SPARKLE GLITTER BREAK!!!', '02 Jun 2026 21:13'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'LOUD AND GLITTERY (JUST HOW YOU LIKE IT)', '02 Jun 2026 21:11'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'AWAWAWAWA', '02 Jun 2026 21:08'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WAG UR TAIL 2 THIS! (PAWS UP ON THE DANCEFLOOR!)', '02 Jun 2026 21:04'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'GLITTER GLITTER GLITTER', '02 Jun 2026 21:01'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'WOOF WOOF!', '02 Jun 2026 20:58'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'retroslop!', '02 Jun 2026 20:57'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU KNOW WHAT?', '02 Jun 2026 20:55'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'THEY''RE PLAYING PIANO IN THE DARK', '02 Jun 2026 20:52'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EVIL (KUZU WANTS YOU TO THINK THAT HE''S EVIL BUT HE''S REALLY JUST A SWEETHEART)', '02 Jun 2026 20:50'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'YOU THINK YOU CAN WIN WITH THAT BOARD?!', '02 Jun 2026 20:46'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'DO THE OTTER DANCE!', '02 Jun 2026 20:44'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'DO THE OTTER DANCE!', '02 Jun 2026 16:17'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'IN YOUR ARMS', '02 Jun 2026 16:14'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'EAT UR GUTZ!!!', '02 Jun 2026 16:12'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'SODA POP FIZZ!', '02 Jun 2026 16:09'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'HEY KUZU', '02 Jun 2026 16:07'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'MADE WITH HONEY', '02 Jun 2026 16:01'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'GLITTER IS TOO HYPER FOR PEARL!', '02 Jun 2026 15:59'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '01 Jun 2026 22:01'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '01 Jun 2026 21:59'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '01 Jun 2026 21:55'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '01 Jun 2026 21:53'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '01 Jun 2026 21:49'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '01 Jun 2026 21:45'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '01 Jun 2026 21:44'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '01 Jun 2026 21:41'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '01 Jun 2026 21:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '01 Jun 2026 21:38'::timestamp),
  ('The College Dropout', 'Kanye West', 'Get Em High', '01 Jun 2026 01:29'::timestamp),
  ('The College Dropout', 'Kanye West', 'Never Let Me Down', '01 Jun 2026 00:22'::timestamp),
  ('The College Dropout', 'Kanye West', 'Jesus Walks', '01 Jun 2026 00:19'::timestamp),
  ('The College Dropout', 'Kanye West', 'Spaceship', '01 Jun 2026 00:13'::timestamp),
  ('The College Dropout', 'Kanye West', 'I''ll Fly Away', '01 Jun 2026 00:12'::timestamp),
  ('The College Dropout', 'Kanye West', 'All Falls Down', '01 Jun 2026 00:08'::timestamp),
  ('The College Dropout', 'Kanye West', 'Graduation Day', '01 Jun 2026 00:07'::timestamp),
  ('The College Dropout', 'Kanye West', 'We Don''t Care', '01 Jun 2026 00:03'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'scene kweenz', '31 May 2026 12:18'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'wanna fucking scream!!!', '31 May 2026 11:57'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'old money bitch', '31 May 2026 11:50'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '29 May 2026 22:09'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '29 May 2026 22:07'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '29 May 2026 22:03'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '29 May 2026 22:00'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '29 May 2026 21:57'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '29 May 2026 21:53'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '29 May 2026 21:52'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '29 May 2026 21:49'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '29 May 2026 21:48'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PROTECC ATTACC SEXYBACC', '29 May 2026 21:45'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '29 May 2026 21:43'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'ravestate_909', '29 May 2026 16:18'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '29 May 2026 16:02'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nothing makes sense and i''m lost', '29 May 2026 16:00'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '29 May 2026 15:58'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', '21', '29 May 2026 15:56'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'z-mecha [original]', '29 May 2026 15:54'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'who''s afraid?', '29 May 2026 15:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'puppydog''s lament', '29 May 2026 15:49'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'LONG LIVE THE KING', '29 May 2026 15:45'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'supa girl racer 5', '29 May 2026 15:43'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'this is the daria i''ve ever made', '29 May 2026 15:41'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nice opinion one small issue', '29 May 2026 15:40'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nice opinion one small issue', '28 May 2026 22:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '28 May 2026 21:59'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'your local menace to society', '28 May 2026 21:56'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'v0id', '28 May 2026 21:54'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'gr!ndcore or something idk im hxrny', '28 May 2026 21:52'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'black tar heroin', '28 May 2026 21:50'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nah i''m out of title ideas', '28 May 2026 21:46'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'stay high', '28 May 2026 21:43'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'AUTISM BE DAMNED!', '28 May 2026 21:41'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'sadb0i dariacore', '28 May 2026 21:39'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr [w/ touqai kgb ninoo & shimoda]', '28 May 2026 21:36'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr [w/ touqai kgb ninoo & shimoda]', '28 May 2026 21:35'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'supa girl racer 5', '28 May 2026 21:33'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '28 May 2026 21:31'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'classically trained in dariacore', '28 May 2026 16:38'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'PUPLIFE', '28 May 2026 16:35'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'in and of itself', '28 May 2026 15:51'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'labyrinth', '28 May 2026 15:47'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i can not find my jacket', '28 May 2026 15:46'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'i wish that i learned how to draw so i could be making things that look nice instead of this', '28 May 2026 15:44'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '28 May 2026 15:39'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the end of clear ice', '28 May 2026 15:36'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'the bowling alley', '28 May 2026 15:34'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Unbreakable', '28 May 2026 00:01'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Watch Your Step', '27 May 2026 23:57'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Blam-Oh!', '27 May 2026 23:54'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Get Up!!', '27 May 2026 23:51'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Fun In The Sun!', '27 May 2026 23:49'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'ZOMG?!', '27 May 2026 23:45'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Where You Were', '27 May 2026 23:43'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Diginova', '27 May 2026 23:41'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Adrenaline', '27 May 2026 23:39'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Glory To All', '27 May 2026 23:37'::timestamp),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', 'Weary', '27 May 2026 23:35'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '27 May 2026 22:02'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '27 May 2026 21:59'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '27 May 2026 21:57'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '27 May 2026 21:54'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '27 May 2026 21:52'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '27 May 2026 21:47'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '27 May 2026 21:39'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '27 May 2026 21:34'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'AMOSTRADINHA', '27 May 2026 16:11'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'this time!', '26 May 2026 22:05'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '26 May 2026 22:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'camp hill PA', '26 May 2026 21:57'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '26 May 2026 21:54'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'make it make sense!', '26 May 2026 21:51'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '26 May 2026 21:49'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'the CONE ZONE!', '26 May 2026 21:46'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '26 May 2026 21:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Tryondas Galaxy', '26 May 2026 21:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Your Local Forecast 1133', '26 May 2026 21:38'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Select Your Car!', '26 May 2026 21:36'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '26 May 2026 20:49'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '26 May 2026 20:47'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '26 May 2026 20:44'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '26 May 2026 20:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '26 May 2026 20:39'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '26 May 2026 20:38'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '26 May 2026 20:34'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '26 May 2026 20:29'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'LÁ ELE', '26 May 2026 17:36'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'AMOSTRADINHA', '26 May 2026 17:20'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'LÁ ELE', '26 May 2026 13:38'::timestamp),
  ('AURAMUNDO', 'allendo051', 'PRO BETA NÃO SOBROU NADA', '26 May 2026 11:45'::timestamp),
  ('AURAMUNDO', 'allendo051', 'VBUCKS', '26 May 2026 11:42'::timestamp),
  ('AURAMUNDO', 'allendo051', 'A ADM É TOP', '26 May 2026 11:40'::timestamp),
  ('AURAMUNDO', 'allendo051', 'MODO SICKO SEVEN', '26 May 2026 11:37'::timestamp),
  ('AURAMUNDO', 'allendo051', 'AURAAAAAAAAAAA', '26 May 2026 11:36'::timestamp),
  ('AURAMUNDO', 'allendo051', '10/10 QUE GOSTA DE MEME 2', '26 May 2026 11:34'::timestamp),
  ('AURAMUNDO', 'allendo051', 'AIR FRYER', '26 May 2026 11:32'::timestamp),
  ('AURAMUNDO', 'allendo051', 'AURAAAAAAAAAAA', '26 May 2026 11:29'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'CHOCOLEXX', '26 May 2026 11:27'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'OVERDOSE DE MONSTER', '26 May 2026 11:25'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'TROPA DO TOMATE', '26 May 2026 11:23'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'LÁ ELE', '26 May 2026 11:21'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'DÓ RÉ MI FA SOL LA SIX SEVEN', '26 May 2026 11:20'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'MAKITA', '26 May 2026 11:17'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'AMOSTRADINHA', '26 May 2026 11:15'::timestamp),
  ('AURAMUNDO', 'allendo051', 'MODO SICKO SEVEN', '25 May 2026 22:49'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'CHOCOLEXX', '25 May 2026 22:35'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'OVERDOSE DE MONSTER', '25 May 2026 22:33'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'TROPA DO TOMATE', '25 May 2026 22:31'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Threat Level Midnight', '25 May 2026 22:04'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Distant Rumbling / Closing Remarks', '25 May 2026 22:02'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Hypemanda Mk I', '25 May 2026 22:01'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Ah Uh Oh', '25 May 2026 22:00'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Do You Have Cowboy Hat', '25 May 2026 21:58'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Snaggle Tooth', '25 May 2026 21:57'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Mastodon Matador', '25 May 2026 21:55'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Near Death Bossa Nova', '25 May 2026 21:55'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Tous Les Jours', '25 May 2026 21:53'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Bad at Texting / World''s Last Mango Juul Pod', '25 May 2026 21:51'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'The Big Unit', '25 May 2026 21:49'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Kelly''s Dungeon', '25 May 2026 21:48'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Introductory Remarks', '25 May 2026 21:46'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Cool Hold Music', '25 May 2026 21:45'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Sweet Thing', '25 May 2026 21:43'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'What Went Weird', '25 May 2026 21:41'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Threat Level Midnight', '25 May 2026 21:40'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Distant Rumbling / Closing Remarks', '25 May 2026 21:38'::timestamp),
  ('Bobbing — Singles & Sessions', 'Bobbing', 'Hypemanda Mk I', '25 May 2026 21:37'::timestamp),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', 'kindanervous (>~<)', '25 May 2026 21:35'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'LÁ ELE', '25 May 2026 21:22'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'LÁ ELE', '25 May 2026 21:14'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'DÓ RÉ MI FA SOL LA SIX SEVEN', '25 May 2026 21:13'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'MAKITA', '25 May 2026 21:10'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'AMOSTRADINHA', '25 May 2026 21:08'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '25 May 2026 21:04'::timestamp),
  ('MUITO BASTANTE AURA', 'allendo051', 'AMOSTRADINHA', '25 May 2026 20:44'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'PREY', '25 May 2026 19:52'::timestamp),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', 'VENOMOUS', '25 May 2026 19:50'::timestamp),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', 'old money bitch', '25 May 2026 19:48'::timestamp),
  ('Idaidaida II', 'ida deerz', '8080 West', '25 May 2026 19:44'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '25 May 2026 12:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '25 May 2026 12:51'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '25 May 2026 12:48'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Ok Go Crazy (Fallen Mix)', '25 May 2026 12:46'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '25 May 2026 12:43'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Prayer', '25 May 2026 12:40'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Let Me Go', '25 May 2026 12:36'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '25 May 2026 12:33'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Descended', '25 May 2026 12:30'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '24 May 2026 00:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '24 May 2026 00:40'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '24 May 2026 00:32'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '24 May 2026 00:31'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Tears of a Galaxy', '24 May 2026 00:30'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Gato', '24 May 2026 00:26'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Soft Rain', '24 May 2026 00:21'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Sea Bus', '24 May 2026 00:19'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Werewolf With Pants', '24 May 2026 00:16'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Friendly', '24 May 2026 00:15'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Airplane', '24 May 2026 00:11'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Puzzle', '24 May 2026 00:08'::timestamp),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', 'Do I Know You?', '24 May 2026 00:07'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'over it now!', '23 May 2026 23:19'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'ask dennis!', '23 May 2026 23:14'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '23 May 2026 23:12'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '23 May 2026 23:08'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '5mg EEn', '23 May 2026 23:06'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', 'Changes', '23 May 2026 23:00'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 West', '23 May 2026 22:58'::timestamp),
  ('ida deerz — Singles & Sessions', 'ida deerz', '8080 East', '23 May 2026 22:54'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:53'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:51'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:49'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:47'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:46'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:44'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:43'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:40'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:39'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:38'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:36'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:34'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:33'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:31'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:29'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:27'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:25'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:25'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:23'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:20'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:19'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'dead to me', '23 May 2026 22:18'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'the lake', '23 May 2026 22:16'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'crater', '23 May 2026 22:14'::timestamp),
  ('eel valley — Singles & Sessions', 'eel valley', 'flowers', '23 May 2026 22:13'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
