-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Team Fortress 2', '13 Apr 2026 15:09'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Rise of the Living Bread', '13 Apr 2026 15:07'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'MEDIC!', '13 Apr 2026 15:05'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Saxton''s Dilemma', '13 Apr 2026 15:04'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Soldier of Dance', '13 Apr 2026 15:03'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'The Calm', '13 Apr 2026 15:00'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Yeti Park', '13 Apr 2026 14:57'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Right Behind You', '13 Apr 2026 14:55'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Faster Than a Speeding Bullet', '13 Apr 2026 14:54'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Archimedes', '13 Apr 2026 14:52'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Carousel of Curses', '13 Apr 2026 14:51'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'Misfortune Teller', '13 Apr 2026 14:50'::timestamp),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', 'ROBOTS!', '13 Apr 2026 14:48'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'VERY COOL', '13 Apr 2026 14:47'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'BUMP THE HARDSTYLE TRANCE', '13 Apr 2026 14:44'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'sharding abt hrt shit', '13 Apr 2026 14:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'remeowved something', '13 Apr 2026 14:42'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'wavelength of my feelings pls feel my energy', '13 Apr 2026 14:39'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'drowning timeline of the wavelength', '13 Apr 2026 14:37'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'some kinda chiller hardcore', '13 Apr 2026 14:35'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'unrefined brain activity huh', '13 Apr 2026 14:34'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'FART IN your ass not mine oplaessesese', '13 Apr 2026 14:32'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'ak-gigabab_9122', '13 Apr 2026 14:29'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepyr.tech', '13 Apr 2026 14:26'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the happenstance occurs in an unseemingly manner power withheld above all else dont think to hard', '13 Apr 2026 14:22'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'truly another track where someone pisses herself', '13 Apr 2026 14:21'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'more unknown full of it', '13 Apr 2026 14:19'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'found the feeling', '13 Apr 2026 14:17'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepicarpy.tek', '13 Apr 2026 14:16'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'hound down', '13 Apr 2026 14:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '13 Apr 2026 13:59'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Time', '12 Apr 2026 12:23'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Roommate', '12 Apr 2026 12:21'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', 'Please select an save file', '12 Apr 2026 12:19'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Ammateur', '12 Apr 2026 12:16'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Would You?', '12 Apr 2026 12:15'::timestamp),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', 'Would You?', '12 Apr 2026 12:13'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:31'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:30'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:29'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:28'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:27'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:25'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:23'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:21'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:20'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:20'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:17'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:16'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:14'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:13'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:12'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:11'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 23:09'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:08'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 23:06'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 23:04'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please select an save file', '11 Apr 2026 23:03'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Please complete the Tutorial before uh..', '11 Apr 2026 23:03'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Would You?', '11 Apr 2026 23:02'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Time', '11 Apr 2026 22:59'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Ammateur', '11 Apr 2026 22:57'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Roommate', '11 Apr 2026 22:56'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '10 Apr 2026 20:47'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '10 Apr 2026 20:45'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Transgender', '10 Apr 2026 20:28'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:24'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Kerosene', '10 Apr 2026 20:22'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Transgender', '10 Apr 2026 20:19'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:15'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Kerosene', '10 Apr 2026 20:12'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:11'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:07'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 20:03'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 19:59'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '10 Apr 2026 19:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Sky', '10 Apr 2026 16:28'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Bleeding', '10 Apr 2026 16:05'::timestamp),
  ('68+1 — Singles & Sessions', '68+1', 'here I am', '10 Apr 2026 16:02'::timestamp),
  ('ソルス — Singles & Sessions', 'ソルス', 'Yung Lain - Ciel', '10 Apr 2026 15:59'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'soup', '10 Apr 2026 15:55'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'anything 2', '10 Apr 2026 15:53'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '10 Apr 2026 15:50'::timestamp),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', 'Ftlframe - Subterranean Loner', '10 Apr 2026 15:48'::timestamp),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', 'what we did in the desert', '10 Apr 2026 15:43'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '10 Apr 2026 15:41'::timestamp),
  ('S777N — Singles & Sessions', 'S777N', 's777n - remains of a corrupted file', '10 Apr 2026 15:37'::timestamp),
  ('Missing Music — Singles & Sessions', 'Missing Music', 'Emray - About 10 Hours of making Breakcore', '10 Apr 2026 15:34'::timestamp),
  ('xaptiox — Singles & Sessions', 'xaptiox', 'ariaMATH - xaptiox', '10 Apr 2026 15:31'::timestamp),
  ('Akiba — Singles & Sessions', 'Akiba', 'MOOGCiTY', '10 Apr 2026 15:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'not askin 4 much', '09 Apr 2026 22:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Lore', '09 Apr 2026 22:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 22:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Oh Yeah?', '09 Apr 2026 22:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 21:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 21:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'black tar heroin', '09 Apr 2026 21:50'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'wanna fucking scream!!!', '09 Apr 2026 21:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'feeling lucky', '09 Apr 2026 21:46'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '09 Apr 2026 21:45'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'hound down', '09 Apr 2026 21:41'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'NEWGROUNDS HITMAN', '09 Apr 2026 20:59'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'CATNIP', '09 Apr 2026 20:54'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'Top Hat ''N'' Monocle', '09 Apr 2026 20:49'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'THE PUP MASK BANDIT', '09 Apr 2026 20:43'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'I KILLED JACKAL QUEENSTON', '09 Apr 2026 20:37'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'SUBMEOWER', '09 Apr 2026 20:32'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'TABBY produces worst track ever', '09 Apr 2026 20:28'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'VEGETARIAN', '09 Apr 2026 20:17'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'YEAR OF THE NAUGHTY FOX', '09 Apr 2026 20:09'::timestamp),
  ('Tabby — Singles & Sessions', 'Tabby', 'NEWGROUNDS HITMAN', '09 Apr 2026 20:04'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Plague', '09 Apr 2026 20:03'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Kerosene', '09 Apr 2026 20:02'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Transgender', '09 Apr 2026 20:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 19:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 19:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 19:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '09 Apr 2026 19:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '09 Apr 2026 19:51'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 19:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 19:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 19:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 19:46'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '09 Apr 2026 19:44'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '09 Apr 2026 19:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '09 Apr 2026 19:40'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 19:38'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 19:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 19:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 19:33'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '09 Apr 2026 19:31'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 19:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '09 Apr 2026 19:28'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 19:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 19:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 19:24'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '09 Apr 2026 19:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '09 Apr 2026 19:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 19:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 19:15'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '09 Apr 2026 19:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 19:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 19:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 19:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 19:01'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 19:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 18:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '09 Apr 2026 18:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '09 Apr 2026 18:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 18:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 18:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 18:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '09 Apr 2026 18:48'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '09 Apr 2026 18:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '09 Apr 2026 18:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 18:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 17:23'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 17:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 17:21'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 17:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '09 Apr 2026 17:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 17:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '09 Apr 2026 17:14'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 17:12'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '09 Apr 2026 17:10'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 17:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '09 Apr 2026 17:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 17:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '09 Apr 2026 17:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 17:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 16:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 16:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '09 Apr 2026 16:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '09 Apr 2026 16:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '09 Apr 2026 16:53'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '09 Apr 2026 16:51'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '09 Apr 2026 16:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '09 Apr 2026 16:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '09 Apr 2026 16:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '09 Apr 2026 16:44'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '09 Apr 2026 16:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '09 Apr 2026 16:40'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '09 Apr 2026 16:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '09 Apr 2026 16:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '09 Apr 2026 16:36'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '09 Apr 2026 15:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nice opinion one small issue', '09 Apr 2026 15:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'supa girl racer 5', '09 Apr 2026 15:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'this is the daria i''ve ever made', '09 Apr 2026 15:47'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'wanna fucking scream!!!', '09 Apr 2026 15:44'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '09 Apr 2026 15:42'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'z-mecha', '09 Apr 2026 15:40'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nah i''m out of title ideas', '09 Apr 2026 15:38'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nothing makes sense and i''m lost', '09 Apr 2026 15:33'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'v0id', '09 Apr 2026 15:31'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'old money bitch', '09 Apr 2026 15:28'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'glue monkey', '09 Apr 2026 15:27'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'anesthetic', '09 Apr 2026 15:25'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'sadb0i dariacore', '09 Apr 2026 15:23'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '09 Apr 2026 15:23'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '08 Apr 2026 22:05'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'let me oute!!!', '08 Apr 2026 22:03'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the sus files', '08 Apr 2026 22:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the cashier looked at me weird i don''t know if i can go back', '08 Apr 2026 21:59'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'classically trained in dariacore', '08 Apr 2026 21:58'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'feeling lucky', '08 Apr 2026 21:56'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'new notification dopamine', '08 Apr 2026 21:54'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'move like a freak!', '08 Apr 2026 21:52'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'scene kweenz', '08 Apr 2026 21:49'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bxphomet goatmilk 🜏 666', '08 Apr 2026 21:46'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'rock that microphone', '08 Apr 2026 21:44'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re fake as fuck', '08 Apr 2026 21:42'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bad crack style 2012', '08 Apr 2026 21:40'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'terminal oden od', '08 Apr 2026 21:38'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'hound down', '08 Apr 2026 21:36'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'gr!ndcore or something idk im hxrny', '08 Apr 2026 21:35'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '08 Apr 2026 21:34'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'stay high', '08 Apr 2026 21:31'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'CIRCLONT6A', '08 Apr 2026 19:48'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'fz pseudotimestretch+e+3 [138.85]', '08 Apr 2026 19:47'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'XMAS_EVET10', '08 Apr 2026 19:45'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'tearing meat', '08 Apr 2026 17:03'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'rainier', '08 Apr 2026 17:01'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'my teeth will free you', '08 Apr 2026 16:58'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'with all my heart', '08 Apr 2026 16:55'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'it''s ok', '08 Apr 2026 16:52'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'c.e.d.', '08 Apr 2026 16:50'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'dogwhistle', '08 Apr 2026 16:47'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'her body my cathedral', '08 Apr 2026 16:43'::timestamp),
  ('sixwing — Singles & Sessions', 'sixwing', 'choke it out!', '08 Apr 2026 16:42'::timestamp),
  ('Hellripper — Singles & Sessions', 'Hellripper', 'The Art of Resurrection', '08 Apr 2026 16:40'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re fake as fuck', '08 Apr 2026 14:11'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'scene kweenz', '08 Apr 2026 14:08'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nice opinion one small issue', '08 Apr 2026 14:06'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'move like a freak!', '08 Apr 2026 14:04'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex', '08 Apr 2026 14:02'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'stay high', '08 Apr 2026 14:00'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'old money bitch', '08 Apr 2026 13:57'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'nah i''m out of title ideas', '08 Apr 2026 13:54'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'tinnitus speedrun any% wr', '08 Apr 2026 13:50'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'v0id', '08 Apr 2026 13:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'your local menace to society', '08 Apr 2026 13:45'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bxphomet goatmilk 🜏 666', '08 Apr 2026 13:42'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'funnycore twerkhouse', '07 Apr 2026 22:08'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'sadb0i dariacore', '07 Apr 2026 22:06'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'let me oute!!!', '07 Apr 2026 22:04'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'rock that microphone', '07 Apr 2026 22:01'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the sus files', '07 Apr 2026 22:00'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bitingmynails / bitingmylips', '07 Apr 2026 21:58'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'z-mecha', '07 Apr 2026 21:56'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'feeling lucky', '07 Apr 2026 21:55'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', '21', '07 Apr 2026 21:53'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'terminal oden od', '07 Apr 2026 21:51'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'the cashier looked at me weird i don''t know if i can go back', '07 Apr 2026 21:48'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'black tar heroin', '07 Apr 2026 21:46'::timestamp),
  ('fur:trash — Singles & Sessions', 'fur:trash', 'bad crack style 2012', '07 Apr 2026 21:44'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'MYSPACE BANGER 3008', '07 Apr 2026 21:42'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THE MAKE UP BEAR', '07 Apr 2026 21:40'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'NAMx', '07 Apr 2026 21:35'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ÄLSKAR DIG!!', '07 Apr 2026 21:31'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'BUMP THE HARDSTYLE TRANCE', '07 Apr 2026 20:45'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'anti-nepyr.tech', '07 Apr 2026 20:43'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'tihjygu', '07 Apr 2026 20:40'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'truly another track where someone pisses herself', '07 Apr 2026 20:39'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'drowning timeline of the wavelength', '07 Apr 2026 20:32'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'FART IN your ass not mine oplaessesese', '07 Apr 2026 20:31'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'the happenstance occurs in an unseemingly manner power withheld above all else dont think to hard', '07 Apr 2026 20:27'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DRAIN PUPPY MAIL ME IMMEDIATELY', '07 Apr 2026 19:56'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'FEED YOUR LOCAL MAILPUP', '07 Apr 2026 19:53'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'BORIS JOHNSON DEATH INCANTATION', '07 Apr 2026 19:51'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'LET ME MAIL YOUR PACKAGE', '07 Apr 2026 19:50'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'ASS UP!', '07 Apr 2026 19:47'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HARDER DADDY', '07 Apr 2026 19:45'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '07 Apr 2026 18:56'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '07 Apr 2026 18:54'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '07 Apr 2026 18:53'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '07 Apr 2026 18:01'::timestamp),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', 'Sore Point', '07 Apr 2026 17:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '07 Apr 2026 17:58'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '07 Apr 2026 17:56'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '07 Apr 2026 15:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '07 Apr 2026 15:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '07 Apr 2026 15:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '07 Apr 2026 15:40'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '07 Apr 2026 15:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '07 Apr 2026 15:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '07 Apr 2026 15:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '07 Apr 2026 15:33'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '07 Apr 2026 15:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '07 Apr 2026 15:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '07 Apr 2026 15:28'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '07 Apr 2026 15:27'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '07 Apr 2026 15:24'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '07 Apr 2026 15:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '07 Apr 2026 15:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '07 Apr 2026 15:19'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '07 Apr 2026 15:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '07 Apr 2026 14:46'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '07 Apr 2026 14:44'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '07 Apr 2026 14:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '07 Apr 2026 14:42'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '07 Apr 2026 14:36'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '07 Apr 2026 14:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '07 Apr 2026 14:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '07 Apr 2026 14:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '07 Apr 2026 14:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '07 Apr 2026 14:28'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '07 Apr 2026 14:26'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '07 Apr 2026 14:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '07 Apr 2026 14:23'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '07 Apr 2026 14:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '07 Apr 2026 14:21'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'trains not making it', '07 Apr 2026 14:19'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'hexd landscape itself beats harder than a bleeding synth', '07 Apr 2026 14:17'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'fragment of a dunjeon', '07 Apr 2026 14:12'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'TAPECEPTION', '07 Apr 2026 13:57'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'JUNGLEE SPIIT', '07 Apr 2026 13:53'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'aftermath', '07 Apr 2026 13:51'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'kivkin it', '07 Apr 2026 13:48'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'kivkin it', '07 Apr 2026 13:04'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'smomked out', '07 Apr 2026 13:02'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'trains a coming', '07 Apr 2026 12:59'::timestamp),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', 'pls take ur shoes off b4 entering', '07 Apr 2026 12:57'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Insulin', '07 Apr 2026 12:55'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Pale Flesh', '07 Apr 2026 12:54'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Intimate', '07 Apr 2026 12:51'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Pap Smear', '07 Apr 2026 12:49'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Courtship Dating', '07 Apr 2026 12:46'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Vanished', '07 Apr 2026 12:44'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Magic Spells', '07 Apr 2026 12:36'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Reckless', '07 Apr 2026 12:35'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', '1991', '07 Apr 2026 12:33'::timestamp),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', 'Through the Hosiery', '07 Apr 2026 12:31'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '06 Apr 2026 23:46'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '06 Apr 2026 23:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '06 Apr 2026 23:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '06 Apr 2026 23:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '06 Apr 2026 23:38'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '06 Apr 2026 23:37'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '06 Apr 2026 23:36'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '06 Apr 2026 23:34'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '06 Apr 2026 23:32'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '06 Apr 2026 23:30'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '06 Apr 2026 23:29'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '06 Apr 2026 23:28'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '06 Apr 2026 23:26'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '06 Apr 2026 23:25'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '06 Apr 2026 23:22'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '06 Apr 2026 23:20'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '06 Apr 2026 23:18'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '06 Apr 2026 23:17'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '06 Apr 2026 23:16'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '06 Apr 2026 23:14'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '06 Apr 2026 23:12'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '06 Apr 2026 23:10'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '06 Apr 2026 23:08'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '06 Apr 2026 23:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '06 Apr 2026 23:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '06 Apr 2026 23:04'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '06 Apr 2026 23:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '06 Apr 2026 23:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '06 Apr 2026 22:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '06 Apr 2026 22:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '06 Apr 2026 22:55'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '06 Apr 2026 22:54'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '06 Apr 2026 22:06'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Closing Up', '06 Apr 2026 22:05'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Real Fellas', '06 Apr 2026 22:03'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '06 Apr 2026 22:02'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Know I Hear You', '06 Apr 2026 22:00'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '06 Apr 2026 21:59'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '06 Apr 2026 21:57'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '06 Apr 2026 21:53'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Pinata Break', '06 Apr 2026 21:51'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Lost Signal', '06 Apr 2026 21:49'::timestamp),
  ('FEM&M — Singles & Sessions', 'FEM&M', 'Input Control', '06 Apr 2026 21:47'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Queen', '06 Apr 2026 21:46'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Berdly', '06 Apr 2026 21:46'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Pandora Palace', '06 Apr 2026 21:44'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'It''s Pronounced Rules', '06 Apr 2026 21:43'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'The Dark Truth', '06 Apr 2026 21:42'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Cyber Battle', '06 Apr 2026 21:41'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'NOW''S YOUR CHANCE TO BE A', '06 Apr 2026 21:40'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Attack of the Killer Queen', '06 Apr 2026 21:38'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Spamton', '06 Apr 2026 21:37'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Holiday Studio', '06 Apr 2026 21:37'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Lost Girl', '06 Apr 2026 21:36'::timestamp),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', 'Bluebird of Misfortune', '06 Apr 2026 21:35'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alive', '06 Apr 2026 20:52'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Rainy Day', '06 Apr 2026 20:50'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bright Stuff', '06 Apr 2026 20:49'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Leave u GONE', '06 Apr 2026 20:47'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'I Feel Alright', '06 Apr 2026 20:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '06 Apr 2026 20:43'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Gorveve', '06 Apr 2026 20:41'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Please Hold', '06 Apr 2026 20:40'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Flashback', '06 Apr 2026 20:39'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Fusion Core', '06 Apr 2026 20:36'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '06 Apr 2026 20:28'::timestamp),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', 'LCONDATRACK - HERE WE GO AGAIN', '06 Apr 2026 20:24'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
