-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.albums (title, artist, release_year, genre, cover_url, description, plays) VALUES
  ('Frizk — Singles & Sessions', 'Frizk', NULL, NULL, NULL, 'Listened 382 times. Top tracks: Select Your Car!, I Wish It Were Colder, Tryondas Galaxy, Blue Raspberry Field, give it a little more.', 382),
  ('fur:trash — Singles & Sessions', 'fur:trash', NULL, NULL, NULL, 'Listened 172 times. Top tracks: anesthetic, funnycore twerkhouse, bitingmynails / bitingmylips, tinnitus speedrun any% wr, you''re finally awake sussy baka? u must''ve hit ur head hard c''mon let''s go listen 2 skrillex.', 172),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', NULL, NULL, NULL, 'Listened 146 times. Top tracks: HEWWO KITTY! >:3c, LET ME MAIL YOUR PACKAGE, WASP RAVE, ASS UP!, HARDER DADDY.', 146),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', NULL, NULL, NULL, 'Listened 113 times. Top tracks: i need 2 feel reality, first love theory, disappearing until i feel better, wonderful ending see u later, overthinking.', 113),
  ('SPARKLEWOLF RADIO — Singles & Sessions', 'SPARKLEWOLF RADIO', NULL, NULL, NULL, 'Listened 100 times. Top tracks: the music that plays in my dumb little critter brain, retroslop!, YOU THINK YOU CAN WIN WITH THAT BOARD?!, EAT UR GUTZ!!!, SILLY PUPPY!.', 100),
  ('ida deerz — Singles & Sessions', 'ida deerz', NULL, NULL, NULL, 'Listened 88 times. Top tracks: 8080 West, over it now!, Changes, ask dennis!, make it make sense!.', 88),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', NULL, NULL, NULL, 'Listened 86 times. Top tracks: anything 2, Tropical Nights, Bleeding, Sky, OK Go Crazy - Winter Mix.', 86),
  ('r u s s e l b u c k — Singles & Sessions', 'r u s s e l b u c k', NULL, NULL, NULL, 'Listened 83 times. Top tracks: b-b-BASS DOWN LOW, FLY WITH ME, HERE FOR A GOOD TIME NOT A LONG TIME, Evil Music For BAD DOGS, Just Be Competent.', 83),
  ('David Wojciechowski and Victor Fritzsche — Singles & Sessions', 'David Wojciechowski and Victor Fritzsche', NULL, NULL, NULL, 'Listened 83 times. Top tracks: Soft Rain, Puzzle, Airplane, Friendly, Gato.', 83),
  ('Vertigoaway — Singles & Sessions', 'Vertigoaway', NULL, NULL, NULL, 'Listened 81 times. Top tracks: drowning timeline of the wavelength, truly another track where someone pisses herself, the happenstance occurs in an unseemingly manner power withheld above all else dont think to hard, kivkin it, gali.9221.', 81),
  ('goreshit — Singles & Sessions', 'goreshit', NULL, NULL, NULL, 'Listened 67 times. Top tracks: death of the candy raver, banfield''s crazy fingers, crunch bunch car crash, (still) too young, stop me if you''ve heard this one..', 67),
  ('MUITO BASTANTE AURA', 'allendo051', NULL, NULL, NULL, 'Listened 60 times. Top tracks: AMOSTRADINHA, LÁ ELE, MAKITA, TROPA DO TOMATE, OVERDOSE DE MONSTER.', 60),
  ('Bobbing — Singles & Sessions', 'Bobbing', NULL, NULL, NULL, 'Listened 60 times. Top tracks: Threat Level Midnight, Near Death Bossa Nova, Hypemanda Mk I, Snaggle Tooth, Mastodon Matador.', 60),
  ('PatoFlamejanteTV — Singles & Sessions', 'PatoFlamejanteTV', NULL, NULL, NULL, 'Listened 52 times. Top tracks: Ammateur, Roommate, Sore Point, Time, Please complete the Tutorial before uh...', 52),
  ('suburban daredevil', 'wifiskeleton', NULL, NULL, NULL, 'Listened 49 times. Top tracks: whore, my twenty first reason </3, i keep calling ... (w/ jaydes), i don''t think we''ll ever find him, party.', 49),
  ('GLITTER IN THE BIG CITY!', 'SPARKLEWOLF RADIO', NULL, NULL, NULL, 'Listened 46 times. Top tracks: PARTY LIEK ITS 2012!, WHY DO THEY FEAR WHAT THEY CAN''T SEE?, ABYSSAL HEART, GL1773R ERROR CRASH LOG, SODA POP FIZZ!.', 46),
  ('eightiesheadachetape — Singles & Sessions', 'eightiesheadachetape', NULL, NULL, NULL, 'Listened 46 times. Top tracks: what we did in the desert, the bowling alley, labyrinth, i can not find my jacket, i wish that i learned how to draw so i could be making things that look nice instead of this.', 46),
  ('PASSENGERPRINCESS', 'passengerprincess', NULL, NULL, NULL, 'Listened 44 times. Top tracks: CREDIT CARD, PREY, 4K CARPET, TUMMY, VENOMOUS.', 44),
  ('Toby Fox — Singles & Sessions', 'Toby Fox', NULL, NULL, NULL, 'Listened 42 times. Top tracks: Cyber Battle, Quiet Autumn, Queen, Berdly, Pandora Palace.', 42),
  ('hybrid monster machines of the lesser spotted bastard', 'goreshit', NULL, NULL, NULL, 'Listened 32 times. Top tracks: death of the candy raver, the eternal march of the bastard squad, total fucking stabbage, you''re just being weird for the sake of it., betty boothroyd''s holiday dancer.', 32),
  ('Valve Studio Orchestra — Singles & Sessions', 'Valve Studio Orchestra', NULL, NULL, NULL, 'Listened 32 times. Top tracks: The Art of War, Dapper Cadaver, It Hates Me So Much, Mercenary Park, Saluting the Fallen.', 32),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', NULL, NULL, NULL, 'Listened 30 times. Top tracks: AZRAEL-II - MiKU MUST DiE, MAILPUP - LET ME MAIL YOUR PACKAGE, MAILPUP - HARDER DADDY, AZRAEL-II - POWERHAUS 2014, MAILPUP - ASS UP!.', 30),
  ('internet brainrot', 'tdstr', NULL, NULL, NULL, 'Listened 27 times. Top tracks: ode to brostep, everyydiie, the youtube poop movement, welcome to the wonderful world of, unflinchingly bleak.', 27),
  ('eel valley — Singles & Sessions', 'eel valley', NULL, NULL, NULL, 'Listened 26 times. Top tracks: flowers, dead to me, the lake, crater.', 26),
  ('Crystal Castles — Singles & Sessions', 'Crystal Castles', NULL, NULL, NULL, 'Listened 24 times. Top tracks: Vanished, Transgender, Kerosene, Plague, Insulin.', 24),
  ('Sutured Self', 'Deerxing', NULL, NULL, NULL, 'Listened 17 times. Top tracks: Another Form, IV Drip, Forager, Creature Feature, Trouble.', 17),
  ('passengerprincess — Singles & Sessions', 'passengerprincess', NULL, NULL, NULL, 'Listened 17 times. Top tracks: VENOMOUS, PREY, TUMMY, DANCE ALL NIGHT, PUPPY 4EVER.', 17),
  ('AURAMUNDO', 'allendo051', NULL, NULL, NULL, 'Listened 16 times. Top tracks: MODO SICKO SEVEN, AURAAAAAAAAAAA, VBUCKS, PRO BETA NÃO SOBROU NADA, AIR FRYER.', 16),
  ('Blue Hour Mind', 'Frizk', NULL, NULL, NULL, 'Listened 16 times. Top tracks: I Wish It Were Colder, By The Trees, Select Your Car!, Your Local Forecast 1133, Frizk - Your Local Forecast 1133.', 16),
  ('Hellripper — Singles & Sessions', 'Hellripper', NULL, NULL, NULL, 'Listened 16 times. Top tracks: Coronach, Sculptor''s Cave, The Art of Resurrection, Hunderprest, Kinchyle.', 16),
  ('xaptiox — Singles & Sessions', 'xaptiox', NULL, NULL, NULL, 'Listened 16 times. Top tracks: soup, ariaMATH - xaptiox.', 16),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', NULL, NULL, NULL, 'Listened 16 times. Top tracks: Petiatil Cx Htdui, CIRCLONT6A, fz pseudotimestretch+e+3 [138.85], XMAS_EVET10, Nanou2.', 16),
  ('sixwing — Singles & Sessions', 'sixwing', NULL, NULL, NULL, 'Listened 15 times. Top tracks: choke it out!, tearing meat, it''s ok, her body my cathedral, rainier.', 15),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', NULL, NULL, NULL, 'Listened 15 times. Top tracks: 6arelyhuman - Party Like The 80''s (w/ asteria & kets4eki) [Official Lyric Video], 6arelyhuman - Faster N Harder (Official Audio), 6arelyhuman - DDR (Dance Dance Revolution) [Official Music Video], 6arelyhuman - CR4CK HOUSE (Official Audio), 6arelyhuman asteria - BLOODBATH (Official Music Video).', 15),
  ('Tabby — Singles & Sessions', 'Tabby', NULL, NULL, NULL, 'Listened 14 times. Top tracks: YEAR OF THE NAUGHTY FOX, NEWGROUNDS HITMAN, VEGETARIAN, CATNIP, Top Hat ''N'' Monocle.', 14),
  ('68+1 — Singles & Sessions', '68+1', NULL, NULL, NULL, 'Listened 14 times. Top tracks: here I am, your eyes.', 14),
  ('verti & rains'' trek through the hexd landscape', 'Vertigoaway', NULL, NULL, NULL, 'Listened 13 times. Top tracks: lake of shadows-dry spell, ritual rave, crashed, i never fukd a bih w a prolap, d8imension hole.', 13),
  ('opal', 'LulaMoon', NULL, NULL, NULL, 'Listened 12 times. Top tracks: crescent, gen3mlp (feat. robin''s ghost), ears perk up (feat. CREEPYSUSIE), purrrfect (feat. dis / vinylcat), tropicana cookies (feat Samad M.).', 12),
  ('I', 'Crystal Castles', NULL, NULL, NULL, 'Listened 12 times. Top tracks: Tell Me What to Swallow, Black Panther, Reckless, Through the Hosiery, Knights.', 12),
  ('FANSERVICE', 'MAILPUP', NULL, NULL, NULL, 'Listened 11 times. Top tracks: DANCING WITH SOLVEIG, HARDER DADDY, FEED YOUR LOCAL MAILPUP, DRAIN PUPPY MAIL ME IMMEDIATELY, BORIS JOHNSON DEATH INCANTATION.', 11),
  ('Something Evil Will Happen OST Vol. 1', 'sorakai', NULL, NULL, NULL, 'Listened 11 times. Top tracks: Unbreakable, Watch Your Step, Blam-Oh!, Get Up!!, Fun In The Sun!.', 11),
  ('lovefool', 'wifiskeleton', NULL, NULL, NULL, 'Listened 10 times. Top tracks: back to my day job, lovefool demo, sleep through youre alarms your not well, it was just a dream silly girl return to your peaceful slumber, i was 13 in 2017 and didnt have a cat.', 10),
  ('pony', 'wifiskeleton', NULL, NULL, NULL, 'Listened 10 times. Top tracks: pony, Bipolar, im a monster in your real life, Stupid, stop reminding me im human.', 10),
  ('MAILPUP', 'MAILPUP', NULL, NULL, NULL, 'Listened 10 times. Top tracks: MY DOG RUNS ON SOYLENT, HEWWO! ÒwÓ, MYSPACE BANGER 3008, I REALLY REALLY REALLY HATE THE WORLD BUT THAT''S OK AT LEAST I''VE GOT MY GABBER DRUM, NAMx (MAILPUP flip).', 10),
  ('strxwberrymilk — Singles & Sessions', 'strxwberrymilk', NULL, NULL, NULL, 'Listened 10 times. Top tracks: The Sky Is Purple, Pink Skirts Are Really Sweet, Parking Stress, MP40 (Rawlin'' Mix), Meteor feat. Meeno Wave.', 10),
  ('No Agreements — Singles & Sessions', 'No Agreements', NULL, NULL, NULL, 'Listened 10 times. Top tracks: GnB Chili - Save Me, GnB Chili - Save Me (Disavowed).', 10),
  ('Monarch of Monsters', 'Vylet Pony', NULL, NULL, NULL, 'Listened 9 times. Top tracks: Pest, Sludge, Princess Cuckoo, The Wallflower Equation, Vitality Glitch.', 9),
  ('gali.inveraph//THE WELL', 'Vertigoaway', NULL, NULL, NULL, 'Listened 9 times. Top tracks: the well, the vile spawn-aborted, fullbright, rebenge of the sighted, gali.9221.', 9),
  ('hikikomori days', 'Shoebill', NULL, NULL, NULL, 'Listened 8 times. Top tracks: zOmfg RAVE HARD, improvised mashcore, Dancecore Dirtbag, awesome dj, four eighteen.', 8),
  ('Love Letter To My World', 'strxwberrymilk', NULL, NULL, NULL, 'Listened 8 times. Top tracks: Meteor feat. Meeno Wave, MP40 (Rawlin'' Mix), Music First feat. all due & onacide, Go With The Flow, Blowing My Mind.', 8),
  ('goretrance 9', 'goreshit', NULL, NULL, NULL, 'Listened 8 times. Top tracks: scotch cherries, goretrance 9 (get happy or get fucked ''97), hot as balls, wasting my time, the dancecore element.', 8),
  ('The College Dropout', 'Kanye West', NULL, NULL, NULL, 'Listened 8 times. Top tracks: Get Em High, Never Let Me Down, Jesus Walks, Spaceship, I''ll Fly Away.', 8),
  ('ソルス — Singles & Sessions', 'ソルス', NULL, NULL, NULL, 'Listened 8 times. Top tracks: Yung Lain - Ciel.', 8),
  ('Missing Music — Singles & Sessions', 'Missing Music', NULL, NULL, NULL, 'Listened 8 times. Top tracks: Emray - About 10 Hours of making Breakcore.', 8),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', NULL, NULL, NULL, 'Listened 8 times. Top tracks: Die Sterne, Edwin Rosen - Vertigo, Die Sonne in deinem Zimmer, Edwin Rosen - 21 Nächte wach, kontrollverlust.', 8),
  ('tasanee — Singles & Sessions', 'tasanee', NULL, NULL, NULL, 'Listened 8 times. Top tracks: crystal castles - suffocation.', 8),
  ('Snuffles — Singles & Sessions', 'Snuffles', NULL, NULL, NULL, 'Listened 8 times. Top tracks: THIS THOUGHT - Frizk & snuffles.', 8),
  ('MARCELINHO CYBERJAMS', 'Marcelinho MeteBala', NULL, NULL, NULL, 'Listened 7 times. Top tracks: Spellbound/Cheiro de Pika feat. MC Sapato, CyberBruxaria feat. BRVXO, Marcelo Mizer, Foguetão, Careless Carol.', 7),
  ('Explorers Of The Internet — Singles & Sessions', 'Explorers Of The Internet', NULL, NULL, NULL, 'Listened 7 times. Top tracks: Lois, Lil Jon has trouble with his math test, Drum? And Bass, need feedback plz, The Drop.', 7),
  ('hkmori — Singles & Sessions', 'hkmori', NULL, NULL, NULL, 'Listened 7 times. Top tracks: 0xff.', 7),
  ('Akiba — Singles & Sessions', 'Akiba', NULL, NULL, NULL, 'Listened 7 times. Top tracks: MOOGCiTY.', 7),
  ('S777N — Singles & Sessions', 'S777N', NULL, NULL, NULL, 'Listened 7 times. Top tracks: s777n - remains of a corrupted file.', 7),
  ('FEM&M — Singles & Sessions', 'FEM&M', NULL, NULL, NULL, 'Listened 7 times. Top tracks: Pinata Break, Love Zombie, Beep Beep Bag, BrainSick, Lost Signal.', 7),
  ('stm — Singles & Sessions', 'stm', NULL, NULL, NULL, 'Listened 7 times. Top tracks: runaway girl.', 7),
  ('Floral Shoppe', 'Macintosh Plus', NULL, NULL, NULL, 'Listened 6 times. Top tracks: ECCOと悪寒ダイビング, HIDDEN PATHWAYイルミナティ, 地理, ライブラリ, 花の専門店.', 6),
  ('gnb', 'goreshit', NULL, NULL, NULL, 'Listened 6 times. Top tracks: hold my hand, unnatural, lonely, dreamer, fine night.', 6),
  ('Forgotten Arcade', 'Frizk', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Bright Stuff, Flashback, Real Fellas, Gorveve, Fusion Core.', 6),
  ('II', 'Crystal Castles', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Empathy, Year of Silence, Baptism, Doe Deer, Celestica.', 6),
  ('fur:core VII (puppy radio 24/7)', 'fur:trash', NULL, NULL, NULL, 'Listened 6 times. Top tracks: old money bitch, hound down, scene kweenz, wanna fucking scream!!!, ravestate_909.', 6),
  ('621 gecs — Singles & Sessions', '621 gecs', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Femboifoxxx, femboifoxxx (ALIXI remix), femboifoxxx (loud equals funny vip), GOTH BITCH DUB.', 6),
  ('BGM for an Game that Doesn''t Exists', 'PatoFlamejanteTV', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Would You?, Roommate, Ammateur, Please select an save file.', 6),
  ('theuppermostinlife — Singles & Sessions', 'theuppermostinlife', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Ftlframe - Subterranean Loner.', 6),
  ('IX Fall$ — Singles & Sessions', 'IX Fall$', NULL, NULL, NULL, 'Listened 6 times. Top tracks: IX FALL$ - buried yet so frail.', 6),
  ('Kyra — Singles & Sessions', 'Kyra', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Romantic 2.', 6),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', NULL, NULL, NULL, 'Listened 6 times. Top tracks: Japan.', 6),
  ('Return Of The Rave', 'Spongebob Squarewave', NULL, NULL, NULL, 'Listened 5 times. Top tracks: Doomerz, I Want It THAT Way, Witney Riddim, Smallman Anthem (Party Dont Stop), Get Busy Spongebob.', 5),
  ('Mashcore Punishment', 'DJKurara', NULL, NULL, NULL, 'Listened 5 times. Top tracks: Wake Heart Breakcore, Reason Of Dance, Clarity The Big Boss, Absurd Fuck To The Pop Music, Last First Kingdom.', 5),
  ('Idaidaida II', 'ida deerz', NULL, NULL, NULL, 'Listened 5 times. Top tracks: 8080 West, make it make sense!, 5mg EEn (ft. phimtown & foxparkk), the CONE ZONE!.', 5),
  ('wifiskeleton — Singles & Sessions', 'wifiskeleton', NULL, NULL, NULL, 'Listened 5 times. Top tracks: demo #6 (everybody hates fiona), 32gigs of tranny porn, local, walmart, idc what she doin.', 5),
  ('THE RETURN OF SPARKLEWOLF RADIO', 'SPARKLEWOLF RADIO', NULL, NULL, NULL, 'Listened 5 times. Top tracks: MARBLE HORNETS, retroslop!, SPANK YOUR LOCAL SPARKLEWOLF!, WHIMPER FOR ME.', 5),
  ('theSpackster — Singles & Sessions', 'theSpackster', NULL, NULL, NULL, 'Listened 5 times. Top tracks: cookies n'' cream, RK9, camelCase, Nightlight Interlude, POP! THAT! POOLTOY!.', 5),
  ('Not a Furry Album Cover', 'Betu', NULL, NULL, NULL, 'Listened 5 times. Top tracks: Falling Apart, Cry On My Own, Rudy Knows, Alone.', 5),
  ('BGM for an Game that Doesn''t Exists', 'de PatoFlamejanteTV', NULL, NULL, NULL, 'Listened 5 times. Top tracks: Would You?, Time, Roommate, Ammateur.', 5),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', NULL, NULL, NULL, 'Listened 5 times. Top tracks: LCONDATRACK - HERE WE GO AGAIN.', 5),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', NULL, NULL, NULL, 'Listened 5 times. Top tracks: Fishcracks - Slumber Party.', 5);
