-- ============================================================
-- AudioTaste — scrobble-based seed data (GENERATED FILE)
-- Do not edit by hand. Regenerate with:
--   node scripts/parse_scrobbles.mjs
--   node scripts/build_seed.mjs
--
-- Run order (one file per SQL Editor query, after schema.sql):
--   1. seed_01_albums.sql
--   2. seed_02_reviews.sql
--   3. seed_03_scrobbles_*.sql (in filename order)
--
-- Assumes the albums/reviews/scrobbles tables are EMPTY.
-- Owner username: UltimateQuack
-- ============================================================

INSERT INTO public.scrobbles (album_id, artist, title, track, scrobbled_at)
SELECT a.id, s.artist, s.title, s.track, s.scrobbled_at
FROM (VALUES
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '28 Mar 2026 11:56'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '27 Mar 2026 22:13'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '27 Mar 2026 22:12'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '27 Mar 2026 22:10'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '27 Mar 2026 22:07'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '27 Mar 2026 22:06'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Petiatil Cx Htdui', '27 Mar 2026 22:04'::timestamp),
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '27 Mar 2026 22:02'::timestamp),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', 'LCONDATRACK - HERE WE GO AGAIN', '27 Mar 2026 22:00'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Die Sterne', '27 Mar 2026 21:59'::timestamp),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', 'Fishcracks - Slumber Party', '27 Mar 2026 21:54'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '27 Mar 2026 21:51'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '27 Mar 2026 21:46'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '27 Mar 2026 21:44'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '27 Mar 2026 21:42'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '27 Mar 2026 21:40'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '27 Mar 2026 21:39'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '27 Mar 2026 21:37'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '27 Mar 2026 21:35'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '27 Mar 2026 21:33'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '27 Mar 2026 21:32'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '27 Mar 2026 21:09'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '27 Mar 2026 21:06'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DUELING GABBAZ', '27 Mar 2026 21:05'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '27 Mar 2026 21:03'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '27 Mar 2026 21:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '27 Mar 2026 21:01'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'PURPLE SLURPLE', '27 Mar 2026 20:56'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'HEWWO KITTY! >:3c', '27 Mar 2026 20:54'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'THIS ONE''S FOR THE 2000''s FURRIES', '27 Mar 2026 20:52'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'WASP RAVE', '27 Mar 2026 20:50'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - POWERHAUS 2014', '27 Mar 2026 20:06'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - LET ME MAIL YOUR PACKAGE', '27 Mar 2026 20:05'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - FEED YOUR LOCAL MAILPUP', '27 Mar 2026 20:02'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - ASS UP!', '27 Mar 2026 20:00'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - BORIS JOHNSON DEATH INCANTATION', '27 Mar 2026 19:58'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - HARDER DADDY', '27 Mar 2026 19:55'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - MiKU MUST DiE', '27 Mar 2026 19:53'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SVANTE', '27 Mar 2026 19:50'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - MiKU MUST DiE', '27 Mar 2026 19:41'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '27 Mar 2026 19:33'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'Paul Elstak - don''t leave me alone', '27 Mar 2026 19:32'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'ren styler - battle for the thunderdome', '27 Mar 2026 19:28'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'ren styler - ruff', '27 Mar 2026 19:27'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - FEED YOUR LOCAL MAILPUP', '27 Mar 2026 19:24'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - LET ME MAIL YOUR PACKAGE', '27 Mar 2026 19:24'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - HARDER DADDY', '27 Mar 2026 19:21'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'TABBY - GAY ROBOTS', '27 Mar 2026 19:20'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - CR4CK HOUSE', '27 Mar 2026 19:18'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - LET ME MAIL YOUR PACKAGE', '27 Mar 2026 16:10'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - DRAIN PUPPY MAIL ME IMMEDIATELY', '27 Mar 2026 16:08'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - DRAIN PUPPY MAIL ME IMMEDIATELY', '27 Mar 2026 16:06'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - HARDER DADDY', '27 Mar 2026 16:04'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - BORIS JOHNSON DEATH INCANTATION', '27 Mar 2026 16:02'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'TABBY - THIS IS WHO I AM', '27 Mar 2026 15:59'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - LET ME MAIL YOUR PACKAGE', '27 Mar 2026 15:59'::timestamp),
  ('MAILPUP — Singles & Sessions', 'MAILPUP', 'DANCING WITH SVANTE', '27 Mar 2026 15:55'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'TABBY - KILLJOYS 4 EVAH', '27 Mar 2026 15:53'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'MAILPUP - HARDER DADDY', '27 Mar 2026 15:51'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'TABBY - TERMINALLY ONLINE', '27 Mar 2026 15:48'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'ren styler - made with love', '27 Mar 2026 15:36'::timestamp),
  ('bandcamp archiver guy — Singles & Sessions', 'bandcamp archiver guy', 'AZRAEL-II - MiKU MUST DiE', '27 Mar 2026 15:22'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Nanou2', '27 Mar 2026 13:33'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Aphex Twin - On', '27 Mar 2026 13:30'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Jynweythek', '27 Mar 2026 13:27'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'produk 29', '27 Mar 2026 13:22'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Meltphace 6', '27 Mar 2026 13:16'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Acrid Avid Jam Shred', '27 Mar 2026 13:13'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'IZ-US', '27 Mar 2026 13:12'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Petiatil Cx Htdui', '27 Mar 2026 13:06'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Kesson Dalek', '27 Mar 2026 13:04'::timestamp),
  ('Aphex Twin — Singles & Sessions', 'Aphex Twin', 'Avril 14th', '27 Mar 2026 13:02'::timestamp),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', 'Fishcracks - Slumber Party', '27 Mar 2026 12:20'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '27 Mar 2026 12:18'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '27 Mar 2026 12:06'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Die Sterne', '27 Mar 2026 12:05'::timestamp),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', 'LCONDATRACK - HERE WE GO AGAIN', '27 Mar 2026 12:04'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '27 Mar 2026 12:03'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '27 Mar 2026 12:02'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '27 Mar 2026 11:58'::timestamp),
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '27 Mar 2026 11:57'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me', '27 Mar 2026 11:54'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '27 Mar 2026 11:49'::timestamp),
  ('prod.jk8 — Singles & Sessions', 'prod.jk8', 'Japan', '27 Mar 2026 11:48'::timestamp),
  ('Fishcracks — Singles & Sessions', 'Fishcracks', 'Fishcracks - Slumber Party', '27 Mar 2026 00:30'::timestamp),
  ('stm — Singles & Sessions', 'stm', 'runaway girl', '27 Mar 2026 00:28'::timestamp),
  ('GNB CHILI — Singles & Sessions', 'GNB CHILI', 'Tropical Nights', '27 Mar 2026 00:25'::timestamp),
  ('Edwin Rosen — Singles & Sessions', 'Edwin Rosen', 'Die Sterne', '27 Mar 2026 00:18'::timestamp),
  ('LCONDATRACK — Singles & Sessions', 'LCONDATRACK', 'LCONDATRACK - HERE WE GO AGAIN', '27 Mar 2026 00:14'::timestamp),
  ('tasanee — Singles & Sessions', 'tasanee', 'crystal castles - suffocation', '27 Mar 2026 00:10'::timestamp),
  ('Snuffles — Singles & Sessions', 'Snuffles', 'THIS THOUGHT - Frizk & snuffles', '27 Mar 2026 00:07'::timestamp),
  ('Kyra — Singles & Sessions', 'Kyra', 'Romantic 2', '27 Mar 2026 00:05'::timestamp),
  ('No Agreements — Singles & Sessions', 'No Agreements', 'GnB Chili - Save Me (Disavowed)', '27 Mar 2026 00:00'::timestamp),
  ('usedcvnt — Singles & Sessions', 'usedcvnt', 'i need 2 feel reality', '26 Mar 2026 22:45'::timestamp),
  ('Frizk — Singles & Sessions', 'Frizk', 'Bitrate', '26 Mar 2026 22:22'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Party Like The 80''s (w/ asteria & kets4eki) [Official Lyric Video]', '26 Mar 2026 22:06'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Faster N Harder (Official Audio)', '26 Mar 2026 22:04'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - DDR (Dance Dance Revolution) [Official Music Video]', '26 Mar 2026 22:03'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - CR4CK HOUSE (Official Audio)', '26 Mar 2026 22:01'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman asteria - BLOODBATH (Official Music Video)', '26 Mar 2026 21:59'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Party Like The 80''s (w/ asteria & kets4eki) [Official Lyric Video]', '26 Mar 2026 21:56'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Faster N Harder (Official Audio)', '26 Mar 2026 21:54'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - DDR (Dance Dance Revolution) [Official Music Video]', '26 Mar 2026 21:53'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - CR4CK HOUSE (Official Audio)', '26 Mar 2026 21:51'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman asteria - BLOODBATH (Official Music Video)', '26 Mar 2026 21:48'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Party Like The 80''s (w/ asteria & kets4eki) [Official Lyric Video]', '26 Mar 2026 21:46'::timestamp),
  ('6arelyhuman — Singles & Sessions', '6arelyhuman', '6arelyhuman - Faster N Harder (Official Audio)', '26 Mar 2026 21:45'::timestamp)
) AS s(title, artist, track, scrobbled_at)
JOIN public.albums a ON a.artist = s.artist AND a.title = s.title;
